hwy/ops/shared-inl.h

I am trying to compile the jpeg-xl library on 32 bit Windows in Visual Studio and I ran into a compilation issue where `_mm_popcnt_u64` was undefined on 32 bit Windows. This PR adds a custom implementation of PopCount and changes the check to add support for 32 bit compilation on Windows. The code that was used comes from this implementation: https://github.com/shines77/strlen_fast/blob/master/src/strlen_fast/popcnt.h. An other option would be to use `std::popcount` but that requires C++20 and I don't think that should be used already.

Use different implementation for PopCount on 32 bit Windows.

---

hwy/base.h
hwy/nanobenchmark.cc
hwy/targets.cc
hwy/tests/test_util-inl.h

Clang-cl defines both __clang__ and _MSC_VER which causes issues when building highway for windows with clang-cl. These commits allow to build for Windows with clang-cl.

Fix MSVC detection logic and usage

---

hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h

clang-cl defines _MSC_VER which when including <immintrin.h>
causes all the headers for instruction sets not already defined in
the compile line to be excluded. This means that when compiling for
dynamic dispatch targets the required headers are not actually included
when using clang-cl. This patch worksaround the issue by directly
including those targets in that case.

Include immintrin.h headers when using clang-cl.

---

hwy/base.h

__fp16 is defined in riscv_vector.h and this is in vector extension.
So if not using RVV, __fp16 is undefined. So highway shouldn't set
HWY_NATIVE_FLOAT16 without vector extension.
And, actually, since VLEN isn't exported to pre-defined macro for compiler/OS,
kMaxVectorSize is too large size. But it is unnecessary without vector
extension. So if compiler doesn't support vector extension, use default (16).

Consider non-V extensions RISC-V

---

.github/workflows/build_test.yml
CMakeLists.txt

Drive-by: add on-push build-and-test workflows for clang 5/6.
Context:  allow testing of clang-5 build of libjxl (for Mozilla)

Fix clang-5 build

---

CMakeLists.txt

When `CMAKE_CROSSCOMPILING` there may not be any value for `CMAKE_CROSSCOMPILING_EMULATOR`. Only run the command if its not a cross compile or when an emulator is available.

Only run hwy_list_targets if its possible to do so

---

CMakeLists.txt

Setting the target's PREFIX causes ninja to fail claiming multiple rules generate the same executable. The prefix is just a directory name so use RUNTIME_OUTPUT_DIRECTORY instead.

Set RUNTIME_OUTPUT_DIRECTORY for test executables

---

CMakeLists.txt

Split `HWY_EXAMPLES_TESTS_INSTALL` into `HWY_ENABLE_EXAMPLES`, `BUILD_TESTING` and `HWY_ENABLE_INSTALL`. The `HWY_ENABLE_*` values are set to `ON` by default to mirror previous behavior. `BUILD_TESTING` which is created when CTest is included, is set to `ON` by default so use that rather than creating a `HWY_ENABLE_TESTING` value.

Provide individual toggles for build options

---

CMakeLists.txt

Before commit 3ddf82d the following cmake configuration was applied to
the project:
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED YES)
This configuration was applied to all target being build, in particular
hwy_contrib and hwy_test. This commit properly apply
target_compile_features(... PUBLIC cxx_std_11)
to the targets missed.

Properly apply cxx_std_11 compile feature to hwy_contrib/hwy_test

---

hwy/nanobenchmark.cc

It turns out that __MACH__ macro refer to the Mach kernel, which is also
used for GNU/Hurd. Prefer usage of macro __APPLE__ in this case.
This should solve the following compilation error:
nanobenchmark.cc:42:10: fatal error: mach/mach_time.h: No such file or directory
For reference:
* https://developer.apple.com/library/archive/documentation/Porting/Conceptual/PortingUnix/compiling/compiling.html#//apple_ref/doc/uid/TP40002850-SW13

Replace usage of __MACH__ with __APPLE__

---

CMakeLists.txt

HWY_CMAKE_ARM7 requires vfpv4 features.
See also issue #495.

Clarify requirements for option `HWY_CMAKE_ARM7`

---

hwy/contrib/image/image.h
hwy/highway_export.h
hwy/tests/test_util.h

I believe this fixes https://github.com/google/highway/issues/525
By exporting the different symbols based on the different libraries that are built.
I'm not sure if you a test for a dynamically linked build.

Fix exporting symbols between contrib and main dll

---

CMakeLists.txt

libjxl sometimes mixes static and shared targets... So it has BUILD_SHARED_LIBS=ON, but wants to use libhwy.a...
Tested on libjxl: https://github.com/libjxl/libjxl/actions/runs/1841037660

Add an option to override "BUILD_SHARED_LIBS".

---

CMakeLists.txt

blockwise_test.cc : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
rithmetic_test.cc : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj

fix build error  C1128 for MSVC

---

hwy/highway_test.cc

Fixes a compile error caused by implicit function declaration
of memcpy, which is defined in string.h.

hwy/highway_test.cc: include string.h for memcpy

---

CMakeLists.txt

This allows highway targets to be exported at install time (by dependencies).
CMake does not allow build system directories for interface include directories.
https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_INCLUDE_DIRECTORIES.html#creating-relocatable-packages
Required by https://github.com/libsdl-org/SDL_image/pull/189
(libhighway is a dependency of libjxl, which is a dependency of sdl_image)

Wrap build system include directories with generator expression

---

CMakeLists.txt

The copy-inl.h, find-inl.h, and transform-inl.h headers are not installed when building highway with cmake.

Added algo inl files to HWY_CONTRIB_SOURCES

---

hwy/base.h
hwy/contrib/sort/vqsort-inl.h
hwy/detect_compiler_arch.h

- Changing `#pragma unroll` to `#pragma GCC unroll 4` for GCC compiler. The value of 4 can be changed if needed.
This fixes #933 .

Fixing unroll pragma for GCC

---

hwy/detect_targets.h

Multiple architectures were impacted by bug:
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106322
original bug report was reported on MSYS2/i686.

Rework the detection of broken gcc for HWY_BROKEN_EMU128. Fixes #765

---

hwy/ops/arm_neon-inl.h

Symptoms:
In function ‘void vst1_s32(int32_t*, int32x2_t)’,
inlined from ‘void hwy::N_NEON::StoreU(Vec64<int>, Full64<int>, int32_t*)’ at /<<PKGBUILDDIR>>/hwy/ops/arm_neon-inl.h:2804:11,
inlined from ‘void hwy::N_NEON::Store(Vec128<T, N>, Simd<T, kNumLanes, 0>, T*) [with T = int; unsigned int N = 2]’ at /<<PKGBUILDDIR>>/hwy/ops/arm_neon-inl.h:2891:9,
inlined from ‘void hwy::N_NEON::TestSet::operator()(T, D) [with T = int; D = hwy::N_NEON::Simd<int, 2, 0>]’ at /<<PKGBUILDDIR>>/hwy/highway_test.cc:139:10:
/usr/lib/gcc/arm-linux-gnueabihf/12/include/arm_neon.h:10907:27: warning: ‘a’ may be used uninitialized [-Wmaybe-uninitialized]
10907 |   __builtin_neon_vst1v2si ((__builtin_neon_si *) __a, __b);
|   ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This reverts commit …

Remove a warning with gcc 12.x about maybe-uninitialized

---

CMakeLists.txt

hwy cmake build system requires cmake 3.10 since commit 94a72d0c

Remove CMake legacy code logic

---

hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h

This was successfully tested on the test suite of wasm-vips (commit https://github.com/kleisauke/wasm-vips/commit/4ea2b8d4fa9f2f88b9166ff1ff9b4b90cde4c73b).
Resolves: #928

wasm: implement ReorderWidenMulAccumulate and ReorderDemote2To for i16

---

hwy/nanobenchmark.cc

The original rdcycle intent was for timestamp. In RISC-V the proper
equivalent of x86 "rdtsc" is "rdtime".
* http://lists.infradead.org/pipermail/linux-riscv/2022-September/018862.html

Replace rdcycle instruction with rdtime

---

CMakeLists.txt

see #988 for details on why this fix is necessary.
Verified on `mipsel` chroot that this patch removes the `E` flag from the stack for the shared library build.

build: detect architecture and add noexecstack link flag for mips

---

CMakeLists.txt

This option is for projects that include highway as a subproject and do not want to build highway tests or download dependencies

cmake: add option to enable all tests

---

libhwy-test.pc.in

`pkg-config --list-all` otherwise fails with this error:
```
Variable 'exec_prefix' not defined in 'libhwy-test.pc'
```
Copied the `exec_prefix` definition from other `.pc` files in the repo.

Fix missing exec_prefix variable in libhwy-test.pc

---

CMakeLists.txt
cmake/FindAtomics.cmake

It turns out that GCC requires explicitly linking to a library `atomic` in order to support c11/atomics. gcc spec file will not handle it directly at least not on the following Debian archs: armel, m68k, mipsel, powerpc, sh4, sparc64 and riscv64.
Introduce a new cmake module to detect usage of gcc/atomic and add missing library to the link step.
For reference:
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104248
Fixes #1003

cmake: Detect whether or not atomic is needed

---

CMakeLists.txt

This commit will fix the following compilation error on armel:
/usr/bin/ld: CMakeFiles/targets_test.dir/hwy/targets_test.cc.o: undefined reference to symbol '__atomic_store_8@@LIBATOMIC_1.0' /usr/bin/ld: /usr/lib/arm-linux-gnueabi/libatomic.so.1: error adding symbols: DSO missing from command line
Some minor CMake comments shuffling to make sections symetrics.

Make sure to link targets_test against GCC/atomic lib

---

hwy/targets.cc

sys/auxv.h already provides hwcap macros; on glibc, it includes asm/hwcap.h, and on musl, it includes bits/hwcap.h. manually adding asm/hwcap.h increases unnecessary dependencies and chance of conflicting definitions

Don't include asm/hwcap.h

---

CMakeLists.txt
hwy/detect_targets.h
hwy/targets.cc

Not all gcc versions are providing <sys/auxv.h>. Checking for HWY_ARCH_ARM && HWY_COMPILER_GCC_ACTUAL && HWY_OS_LINUX is not sufficient and fail to build in some situations (it was observed for some gcc armv7m toolchains).
This patch adds a check for <sys/auxv.h> and include it only if present.
Signed-off-by: Julien Olivain <ju.o@free.fr>

Check for the presence of <sys/auxv.h>

---

WORKSPACE

While trying to build the sort example (https://github.com/google/highway/tree/master/hwy/contrib/sort), it seems that the Bazel build fails with the following error:
```
ERROR: /home/wjuni/.cache/bazel/_bazel_wjuni/672b509305a448efd90e51f59e30c6de/external/bazel_tools/platforms/BUILD:89:6: in alias rule @bazel_tools//platforms:windows: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: /home/wjuni/.cache/bazel/_bazel_wjuni/672b509305a448efd90e51f59e30c6de/external/bazel_tools/platforms/BUILD:89:6: Analysis of target '@bazel_tools//platforms:windows' failed
ERROR: …
```

Fix Bazel build on Bazel 6.0.0

---

CMakeLists.txt

This setting is set on a particular glibc shipped in current Debian release. This is intentionally done by glibc when targeting minimum kernel 4.8.0 or older with mips hardfloat:
https://github.com/bminor/glibc/blob/595c22ecd8e87a27fd19270ed30fdbae9ad25426/sysdeps/unix/sysv/linux/mips/configure.ac#L138-L143
This backwards compatibility should not be more important than the security hardening of a non-executable stack.
Full reference:
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025436
This reverts commit 97e4b7b74b4ef4f3765e5b09572ce8c583f33c07.
Co-authored-by: Jessica Clarke <jrtc27@debian.org>

Remove explicit setting of noexecstack

---

hwy/ops/scalar-inl.h

Corrected the BitCast function in hwy/ops/scalar-inl.h to copy only sizeof(T) bytes.
The fix in this pull request resolves issue https://github.com/google/highway/issues/1123.

Fixed HWY_SCALAR BitCast to copy only sizeof(T) bytes

---

hwy/ops/arm_neon-inl.h
hwy/ops/rvv-inl.h

This is a revisited patch of PR https://github.com/google/highway/pull/1019, now that I have confirmed that the [`simd-highway`](https://github.com/kleisauke/libvips/tree/simd-highway) branch of libvips also works on SVE (tested using [this script](https://gist.github.com/kleisauke/e085c4f3a546c8fe66604bdf484ff3dd)). This PR allows me to drop commit https://github.com/kleisauke/libvips/commit/0ca6a161a01f4c5129b90fcf1197887e05f8616f. 
Note that commit 36671ddd6c27b1619a2d9d81faefbbd00b6eb947 does not always ensure that the order is preserved on RVV, it could still cause a reorder with `vlen=256` (as noticed in https://github.com/google/highway/pull/1019#issuecomment-1336407603). Let me know if you want me to omit this commit from this PR (and retitle it accordingly).
As a possible …

Ensure `ReorderDemote2To` preserves order on Armv7/RVV

---

hwy/ops/set_macros-inl.h

Highway uses the construct `__attribute__((target(+neon-vfpv4))` for Armv7. The target "+neon-vfpv4" was introduced in gcc 8, in commit [1]. When using a gcc < 8 (for example, like [2]), compilation fails with message:
In file included from /build/highway-1.0.3/hwy/foreach_target.h:81:0,
from /build/highway-1.0.3/hwy/per_target.cc:20:
/build/highway-1.0.3/hwy/per_target.cc: At global scope:
/build/highway-1.0.3/hwy/per_target.cc:23:22: error: attribute(target("+neon-vfpv4")) is unknown
This commit protects the definition of HWY_TARGET_STR only when gcc version 8 or greater is used for armv7.
[1] https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=e87afe54b86c478ae63569e51e7abb67d3fe3fce
[2] https://releases.linaro.org/components/toolchain/binaries/7.3-2018.05/arm-linux-gnueabihf/gcc-linaro-7.3.1 …

Fix compilation for armv7 with gcc < 8

---

hwy/detect_targets.h

When using a armv7 gcc >= 8 toolchain (like [1]) with Highway configured with -DHWY_CMAKE_ARM7=OFF and HWY_ENABLE_CONTRIB=ON, compilation fails with error:
In file included from /build/highway-1.0.3/hwy/ops/arm_neon-inl.h:33,
from /build/highway-1.0.3/hwy/highway.h:358,
from /build/highway-1.0.3/hwy/contrib/sort/shared-inl.h:104,
from /build/highway-1.0.3/hwy/contrib/sort/traits128-inl.h:27,
from /build/highway-1.0.3/hwy/contrib/sort/vqsort_128d.cc:23,
from /build/highway-1.0.3/hwy/foreach_target.h:81,
from /build/highway-1.0.3/hwy/contrib/sort/vqsort_128d.cc:20:
/toolchain/lib/gcc/arm-buildroot-linux-gnueabihf/12.2.0/include/arm_neon.h: In function ‘void hwy::N_NEON::StoreU(Vec128<long long unsigned int, 2>, Full128<long long unsigned int>, uint64_t*)’: …

Fix compilation for armv7 targets with vfp < v4 and gcc >= 8

---

hwy/detect_targets.h
hwy/foreach_target.h
hwy/highway.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/set_macros-inl.h
hwy/targets.cc
hwy/targets.h
hwy/targets_test.cc

I have added support for the HWY_PPC8/HWY_PPC9/HWY_PPC10 targets, and all of the unit tests complete successfully on little-endian HWY_PPC8/HWY_PPC9/HWY_PPC10 targets.
There are some unit tests that fail for big-endian HWY_PPC8/HWY_PPC9/HWY_PPC10 targets, and HWY_BROKEN_TARGETS includes HWY_PPC8/HWY_PPC9/HWY_PPC10 on big-endian HWY_PPC8/HWY_PPC9/HWY_PPC10 targets.
This implementation resolves issue #5.

Added support for VSX on PPC8/PPC9/PPC10 targets

---

hwy/tests/reduction_test.cc

Removes:
[ 86%] Building CXX object CMakeFiles/reduction_test.dir/hwy/tests/reduction_test.cc.o In file included from /home/malat/highway/hwy/foreach_target.h:70,
from /home/malat/highway/hwy/tests/reduction_test.cc:21:
/home/malat/highway/hwy/tests/reduction_test.cc: In instantiation of 'void hwy::N_SCALAR::TestSumOfLanes::operator()(T, D) [with T = short unsigned int; D = hwy::N_SCALAR::Simd<short unsigned int, 1, 0>]':
/home/malat/highway/hwy/tests/test_util-inl.h:184:13:   required from 'static void hwy::N_SCALAR::detail::ForeachCappedR<T, kMul, kMinArg, Test, kPow2>::Do(size_t, size_t) [with T = short unsigned int; long unsigned int kMul = 1; long unsigned int kMinArg = 1; Test = hwy::N_SCALAR::TestSumOfLanes; int kPow2 = 0; size_t = long unsigned int]' …

Remove simple conversion warnings on ppc8/big-endian

---

hwy/detect_targets.h
hwy/ops/set_macros-inl.h

Changed defined(__AVXVNNI__) with defined(__AVX512VNNI__) in hwy/detect_targets.h, and changed avxvnni with avx512vnni in hwy/detect_targets.h.
There are also some x86 CPU's with AVX512 support that support AVX512_VNNI but not the new VEX-encoded AVX-VNNI instructions available on Alder Lake, Sapphire Rapids, and newer Intel CPU's.
Resolves issue #1174

Changed AVXVNNI to AVX512VNNI

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/shared-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/arithmetic_test.cc
hwy/tests/reduction_test.cc

The AbsDiff operation was added for integer vector types as NEON/SVE have instructions that can compute ```|a[i] - b[i]|``` for any of the integer vector types and as PPC9/PPC10 have instructions that can compute ```|a[i] - b[i]|``` for U8/U16/U32 vectors.
The SumsOf8AbsDiff operation was also added as SSE3/SSSE4/AVX2/AVX3 can carry out the ```SumsOf8(AbsDiff(a, b))``` operation through a single psadbw/vpsadbw instruction via the ```_mm_sad_epu8```, ```_mm256_sad_epu8```, and ```_mm512_sad_epu8``` intrinsics.

Added AbsDiff for integer vector types and SumsOf8AbsDiff for U8 vector types

---

hwy/ops/arm_neon-inl.h

AArch64 has support for a non-temporal prefetch for store via the ```prfm PSTL1STRM, memory_location``` instruction, and GCC/Clang/MSVC all have intrinsics for the non-temporal prefetch for store operation.
```__builtin_prefetch(aligned, 1, 0)``` is also already there before the store in the PPC8/PPC9/PPC10 implementation of the Stream operation, which compiles to a ```dcbtst``` instruction on PPC8/PPC9/PPC10.

Added prefetch prior to store for Stream operation on AArch64

---

hwy/ops/ppc_vsx-inl.h

A recent change in Clang 16 and later has changed the return type and parameter types of ```vec_cipher_be``` and ```vec_cipherlast_be``` to ```__vector unsigned char```.
Updated detail::CryptoTag to reflect the changes that have been made for Clang 16 and later.

Updated detail::CryptoTag in ppc_vsx-inl.h for Clang 16 and later

---

hwy/ops/ppc_vsx-inl.h

Fixed issues with compiling ```Vec16<uint8_t> SumOfLanes(Vec16<uint8_t> v)``` on big-endian PPC targets.

Fixed compilation error on big-endian PPC

---

CMakeLists.txt

HAVE_SYS_AUXV_H was being set in the PRIVATE definition list

cmake: Make sure to export public definition

---

hwy/detect_targets.h
hwy/ops/ppc_vsx-inl.h

Some of the Highway unit tests are currently failing on big-endian PPC10 if the ```-mcpu=power10``` and ```-O3``` options are specified (at least with the ppc64 cross compiler on x86_64), but the all of the Highway unit tests pass on big-endian PPC10 if optimizations are disabled.
Also updated BitsFromMask on big-endian HWY_PPC10 to use the PPC8/PPC9 BitsFromMask implementation.

Made changes to BitsFromMask implementation on big-endian PPC10 and added HWY_PPC10 to HWY_BROKEN_TARGETS on big-endian PPC

---

CMakeLists.txt
hwy/targets.cc

Fixes compilation error:
highway/hwy/targets.cc:49:10: fatal error: asm/hwcap.h: No such file or directory
49 | #include <asm/hwcap.h>
|          ^~~~~~~~~~~~~
compilation terminated.

Fix compilation on PPC

---

CMakeLists.txt

Fixes compilation error:
/usr/bin/ld: CMakeFiles/hwy_benchmark.dir/hwy/examples/benchmark.cc.o: undefined reference to symbol '__atomic_load_8@@LIBATOMIC_1.0'
/usr/bin/ld: /usr/lib/powerpc-linux-gnu/libatomic.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Fix compilation of hwy_benchmark on ppc32

---

hwy/targets.cc

The previous version of FlagsFromCPUID failed to clear the HWY_AVX2, HWY_AVX3, HWY_AVX3_DL, and HWY_AVX3_ZEN4 bits on x86_64 if bit 1 of XCR0 is not set. This updated version will clear the HWY_AVX2, HWY_AVX3, HWY_AVX3_DL, and HWY_AVX3_ZEN4 bits on x86_64 if bit 1 of XCR0 is not set.

Fixed FlagsFromCPUID to only clear the AVX2/AVX3 bits on x86_64 if bit 0 of XCR0 is not set

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/scalar-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/demote_test.cc

Added the following new demotion operations:
- DemoteTo from unsigned integer types to signed integer types
- DemoteTo from unsigned integer types to unsigned integer types
- ReorderDemote2To for {i,u}16->{i,u}8, i32->u16, u32->{u,i}16, and {i,u}64->{i,u}32
- OrderedDemote2To for {i,u}16->{i,u}8, {i,u}32->{u,i}16, {i,u}64->{i,u}32, and f32->bf16
Resolves issue #1124

Added more demotion operations

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/scalar-inl.h
hwy/ops/set_macros-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/targets.cc
hwy/tests/combine_test.cc
hwy/tests/convert_test.cc
hwy/tests/logical_test.cc
hwy/tests/reverse_test.cc
hwy/tests/test_util-inl.h

The following operations were added:
- LeadingZeroCount - returns the number of leading zeros for each lane (similar to the AVX3 VPLZCNTD/VPLZCNTQ instruction or the GCC/Clang __builtin_clz intrinsic)
- TrailingZeroCount - returns the number of trailing zeros for each lane (similar to the x86 BSF/TZCNT instruction, the GCC/Clang __builtin_ctz intrinsic, or the MSVC _BitScanForward intrinsic)
- HighestSetBitIndex - returns the index of the highest set bit for each lane (similar to the x86 BSR instruction or the MSVC _BitScanReverse intrinsic)
- OrderedTruncate2To - similar to OrderedDemote2To, but truncates values instead of saturating values
- ReverseLaneBytes - swaps the bytes of each lane, more efficient than TableLookupBytes on NEON/SVE/SVE2/SSE2/PPC9/PPC10, used to implement …

Added LeadingZeroCount and a few more new operations plus bug fixes

---

CMakeLists.txt

`hwy/ops/tuple-inl.h` was forgotten to be added to `CMakeLists.txt` in 486f0d8729da4f40fcabaed785ed3ca50c7138c0.

fix CMake build (missing source file)

---

hwy/ops/ppc_vsx-inl.h

Fixes compilation errors on PPC8/PPC9/PPC10 by adding the missing I8/U8 Reverse operations for PPC8/PPC9/PPC10

Added missing I8/U8 Reverse operations for PPC8/PPC9/PPC10

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/crypto_test.cc

Added the AESKeyGenAssist operation, which can be used to accelerate the AES Key Expansion algorithm, as the AESKeyGenAssist operation for a 128-bit uint8_t vector can be carried out in a single instruction on SSE4/AVX2/AVX3/AVX3_DL targets using the x86 AES-NI AESKEYGENASSIST instruction.
There are two different approaches that can be used to implement the AESKeyGenAssist operation for the other targets.
The first approach, which is used on NEON Crypto/SVE2 Crypto (and for 256-bit/512-bit vectors on AVX3_DL) is to do a U32 DupOdd operation, followed by an AESLastRound operation, followed by a shuffle using the TableLookupBytes operation.
The second approach, which is used by EMU128/PPC8/PPC9/PPC10/NEON_WITHOUT_AES/SSE2/SSSE3/RVV is to do an AES SubBytes operation, followed by a …

Added AESKeyGenAssist operation

---

hwy/contrib/sort/algo-inl.h
hwy/contrib/sort/bench_parallel.cc
hwy/contrib/sort/sort_test.cc
hwy/contrib/sort/vqsort.cc
hwy/contrib/sort/vqsort.h

Changes were made to hwy/contrib/sort/algo-inl.h, hwy/contrib/sort/bench_parallel.cc, hwy/contrib/sort/sort_test.cc, hwy/contrib/sort/vqsort.cc, and hwy/contrib/sort/vqsort.h to fix compilation errors in the GitHub workflow.

Fix vqsort compilation errors

---

hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h

The I16->I32 ReorderWidenMulAccumulate implementation for the AVX3_DL/AVX3_ZEN4 targets has been updated to use the `_mm_dpwssd_epi32`, `_mm256_dpwssd_epi32`, and `_mm512_dpwssd_epi32` intrinsics.
`_mm_dpwssd_epi32(sum, a, b)` is equivalent to `_mm_add_epi32(sum, _mm_madd_epi16(a, b))`, but `_mm_dpwssd_epi32(sum, a, b)` can be carried out using a single VPDPWSSD instruction on the AVX3_DL/AVX3_ZEN4 targets.

Updated AVX3_DL implementation of I16->I32 ReorderWidenMulAccumulate

---

hwy/contrib/sort/vqsort-inl.h

Fix compiler warnings in hwy/contrib/sort/vqsort-inl.h

Fix compiler warnings in hwy/contrib/sort/vqsort-inl.h

---

hwy/ops/ppc_vsx-inl.h

Replaced vec_vctz with vec_cnttz in the PPC9/PPC10 TrailingZeroCount implementation as vec_cnttz is available on GCC 7 and later and Clang 4.0 and later.

Fix clang compilation error with PPC9/PPC10 TrailingZeroCount

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/scalar-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/combine_test.cc
hwy/tests/convert_test.cc

Added the ResizeBitCast and ZeroExtendResizeBitCast operations, which allows a vector to be bit-casted to a smaller or larger vector type.
The ResizeBitCast operation is also usually more efficient than doing a BitCast followed by 2 or more LowerHalf operations in the case where `Lanes(D()) * sizeof(TFromD<D>) <= (Lanes(DFromV<V>()) * sizeof(TFromV<V>)) / 4`.
The ResizeBitCast operation is also usually more efficient than a BitCast operation followed by a ZeroExtendVector operation in the case where `Lanes(D()) * sizeof(TFromD<D>) > Lanes(DFromV<V>()) * sizeof(TFromV<V>)`.
In the case of a ResizeBitCast from a smaller vector type to a larger vector type, the contents of any bytes of the result vector past the past the first `Lanes(DFromV<V>()) * sizeof(TFromV<V>)` bytes of the result …

 Added ResizeBitCast and ZeroExtendResizeBitCast operations

---

hwy/contrib/sort/vqsort-inl.h

Removed HWY_RESTRICT from the keys_end and buf parameters in vqsort-inl.h to fix a compiler error when vqsort-inl.h is compiled with GCC.

Fix GCC compilation error with BaseCase in vqsort-inl.h

---

hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/convert_test.cc
hwy/tests/test_util-inl.h

U8/U16->U64, U8/U16/U32->I64, and I8/I16->I64 PromoteTo operations were added for all targets to ensure consistency across all targets.
SSE4/AVX2/AVX3/RVV can also do I8->I64, I16->I64, U8->U64, and U16->U64 PromoteTo operations using a single instruction.
U8->U64 PromoteTo was also already implemented on the SVE/SCALAR/EMU128 targets.
Also fixed ForPromoteVectors implementation in hwy/tests/test_util-inl.h.

Added U8/U16->U64, U8/U16/U32->I64, and I8/I16->I64 PromoteTo operations

---

hwy/detect_compiler_arch.h
hwy/detect_targets.h
hwy/ops/ppc_vsx-inl.h

Added the HWY_COMPILER_CLANG_PATCHLEVEL macro, which is set to `__clang_patchlevel__` for Clang and to `0` for non-Clang based compilers (or Clang versions detected using `__has_warning` or `__has_attribute` checks).
Updated HWY_BROKEN_PPC10 to mark HWY_PPC10 as non-broken on big-endian PPC with Clang 16.0.1 or later, GCC 11.x, and GCC 12.4 and later (excluding GCC 13.0 and 13.1).
All of the Highway unit tests pass on big-endian HWY_PPC10 when compiled with GCC 11.3 or Clang 16.0.4.
The __builtin_constant_p check for full vectors on PPC8/PPC9/PPC10 has also been refactored out to a new detail::IsConstantRawAltivecVect function (which is used to facilitate GCC/Clang constant folding optimizations for the Xor3, Or3, OrAnd, SumOfLanes, and SumsOf8 operations on PPC8/PPC9/PPC10). …

Made enhancements to PPC10 operations

---

hwy/ops/emu128-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h

Fixed compilation errors with WidenMulPairwiseAdd on PPC and WASM_EMU256 targets.
Also reformatted WidenMulPairwiseAdd on x86 and EMU128.

WidenMulPairwiseAdd compilation fixes and reformatting

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/scalar-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/mask_test.cc

The SetBeforeFirst, SetAtOrBeforeFirst, SetOnlyFirst, and SetAtOrAfterFirst mask operations were implemented as:
- `SetOnlyFirst(m)` is more efficient than `RebindMask(d, Eq(Iota(du, 0), static_cast<TU>(FindFirstTrue(d, m))))` on some targets
- `SetBeforeFirst(m)` is more efficient than `FirstN(d, HWY_MIN(static_cast<size_t>(FindFirstTrue(d, m)), MaxLanes(d)))` on some targets
- `SetAtOrBeforeFirst(m)` is usually more efficient than `Or(SetBeforeFirst(m), SetOnlyFirst(m))`
- RVV has instructions for the SetBeforeFirst, SetAtOrBeforeFirst, and SetOnlyFirst operations
- The implementations of SetBeforeFirst, SetAtOrBeforeFirst, SetOnlyFirst, and SetAtOrAfterFirst in hwy/ops/rvv-inl.h can correctly deal with masks that have more than 128 lanes
- SVE can efficiently carry out the …

Added SetBeforeFirst, SetAtOrBeforeFirst, SetOnlyFirst, and SetAtOrAfterFirst mask ops

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/float_test.cc

There are some targets that have instructions for F64 ApproximateReciprocal and F64 ApproximateReciprocalSqrt, including AVX3, PPC8/PPC9/PPC10, NEON on AArch64, SVE, and RVV.
There are also fallback implementations of ApproximateReciprocal and ApproximateReciprocalSqrt in hwy/ops/generic_ops-inl.h for targets that support F64 vectors but do not have F64 ApproximateReciprocal/ApproximateReciprocalSqrt instructions.

Added ApproximateReciprocal and ApproximateReciprocalSqrt for F64 vectors

---

g3doc/quick_reference.md
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/shift_test.cc

Made the following fixes to `operator<<` and `operator>>` on SSE2/SSSE3/SSE4/AVX2/AVX3/AVX3_DL:
- Implemented `operator>>` for I8 vectors
- Fixed the issue where `operator<<` and `operator>>` generated incorrect results for 1-lane I8/U8/I16/U16/I32/U32 vectors as the  `_mm_sll_epi16`, `_mm_srl_epi16`, `_mm_sra_epi16`, `_mm_sll_epi32`, `_mm_srl_epi32`, and `_mm_sra_epi32` intrinsics (and the SSE2 PSLLW/PSRLW/PSRAW/PSLLD/PSRLD/PSRAD instructions) treat the second argument (shift count) as a uint64_t vector (whose first uint64_t lane is used as the shift count)
- Updated the implementation of `operator<<` and `operator>>` for 1-lane I16/U16 vectors on AVX3 to use the `operator<<(Vec128<uint16_t, N>, Vec128<uint16_t, N>)`, `operator>>(Vec128<int16_t, N>, Vec128<int16_t, N>)`, and …

Fixes to WASM/X86 Shl/Shr and Shl/Shr unit tests

---

hwy/contrib/sort/bench_sort.cc

Fixed issue where bench_sort.cc failed to compile on Clang 6 as the RandomState constructor takes a uint64_t argument.

Fix compilation error with bench_sort.cc on Clang 6

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/swizzle_test.cc
hwy/tests/test_util-inl.h

Added DupEven and DupOdd for I8/U8/I16/U16 vector types.
Also fixed issues on RVV where Reverse2, Reverse4, Reverse8, and ReverseBlocks sometimes fail to compile for vector types that have a fractional LMUL.
Also added a new Per4LaneBlockShuffle operation as Per4LaneBlockShuffle is usually more efficient than TableLookupBytes or TableLookupLanes for I16/U16/I32/U32/F32/I64/U64/F64 vectors.
Per4LaneBlockShuffle is equivalent to SSE2 `_mm_shufflelo_epi16(v, _MM_SHUFFLE(kIdx3, kIdx2, kIdx1, kIdx0))`, SSE2 `_mm_shuffle_epi32(v, _MM_SHUFFLE(kIdx3, kIdx2, kIdx1, kIdx0))`, and AVX2 `_mm256_permute4x64_epi64(v, _MM_SHUFFLE(kIdx3, kIdx2, kIdx1, kIdx0))`.
In the case of I64/U64/F64 vectors that have 4 or more lanes, the Per4LaneBlockShuffle operation does a per 256-bit block shuffle of `v` (same …

Added I8/U8/I16/U16 DupEven/DupOdd and Per4LaneBlockShuffle

---

g3doc/quick_reference.md
hwy/highway_test.cc
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/rvv-inl.h
hwy/ops/shared-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/blockwise_test.cc
hwy/tests/swizzle_test.cc

Added the following new operations:
- InsertBlock - inserts a block of `HWY_MIN(Lanes(DFromV<V>()), 16 / sizeof(TFromV<V>))` lanes to the result vector if `kBlock * 16` is less than `Lanes(DFromV<V>()) * sizeof(TFromV<V>)`. Otherwise, returns `v`.
- ExtractBlock - extracts a block of `HWY_MIN(Lanes(DFromV<V>()), 16 / sizeof(TFromV<V>))` lanes from `v`
- BroadcastBlock - broadcasts a block of `HWY_MIN(Lanes(DFromV<V>()), 16 / sizeof(TFromV<V>))` lanes to all of the other blocks of the result vector
- BroadcastLane - broadcasts a lane to all of the other lanes of the result vector (even in the case of vectors that are larger than 16 bytes)
- NumOfBlocks - returns the number of blocks with `HWY_MIN(Lanes(DFromV<V>()), 16 / sizeof(TFromV<V>))` lanes
Also added `BlockDFromD`, which returns a …

Added InsertBlock, ExtractBlock, BroadcastBlock, BroadcastLane, and NumOfBlocks

---

hwy/timer-inl.h

highway/hwy/timer-inl.h:152:17: error: ‘CLOCK_MONOTONIC’ was not declared in this scope
152 |   clock_gettime(CLOCK_MONOTONIC, &ts);
|                 ^~~~~~~~~~~~~~~
highway/hwy/timer-inl.h:152:3: error: ‘clock_gettime’ was not declared in this scope
152 |   clock_gettime(CLOCK_MONOTONIC, &ts);
|   ^~~~~~~~~~~~~

Fix compilation on fallback POSIX system

---

CMakeLists.txt

Fixes report on powerpc 32 system:
dpkg-shlibdeps: warning: symbol __atomic_store_8 used by debian/libhwy1/usr/lib/powerpc-linux-gnu/libhwy_contrib.so.1.0.5 found in none of the libraries
dpkg-shlibdeps: warning: symbol __atomic_load_8 used by debian/libhwy1/usr/lib/powerpc-linux-gnu/libhwy_contrib.so.1.0.5 found in none of the libraries

Make sure to link hwy_contrib against atomic

---

CMakeLists.txt
hwy/contrib/math/math-inl.h
hwy/contrib/math/math_test.cc

- Added SinCos math function. It computes Sin and Cos at the same time at roughly the same price of a Sin call.
- Implementation for both double and single precision.
- Added the corresponding tests.
Note:
The tests adjust the max ulp based on the target. On some targets (in particular EMU128 and Intel SSE2/3/4) the precision drops.

Added SinCos

---

CMakeLists.txt

Recent cmake version fails to handle both target_link_libraries signatures and reports:
CMake Error at CMakeLists.txt:335 (target_link_libraries):
The plain signature for target_link_libraries has already been used with
the target "hwy_contrib".  All uses of target_link_libraries with a target
must be either all-keyword or all-plain.
The uses of the plain signature are here:
* CMakeLists.txt:324 (target_link_libraries)
This commit fixes this configuration error

Explicit public linking to hwy for hwy_contrib

---

hwy/ops/arm_sve-inl.h

Fixed IndicesFromVec so that SVE debug build will successfully compile

Fix compilation error in SVE debug build

---

hwy/base.h
hwy/contrib/unroller/unroller-inl.h
hwy/contrib/unroller/unroller_test.cc

Updated unroller-inl.h and unroller_test.cc to fix compilation errors with the Highway test suite on clang.

Fixed compilation errors with unroller_test on Clang

---

hwy/contrib/unroller/unroller_test.cc

Updated FindUnit::YInitImpl to fix a compiler warning that causes the build workflow to fail.

Update FindUnit::YInitImpl unroller_test.cc

---

hwy/ops/ppc_vsx-inl.h

Updated GCC PPC10 TernaryLogic inline assembly workaround in ppc_vsx-inl.h to prevent kTernLogOp from being incorrectly sign-extended if kTernLogOp >= 128 is true.

Fix TernaryLogic inline assembly in ppc_vsx-inl.h

---

hwy/base.h
hwy/contrib/sort/algo-inl.h
hwy/contrib/sort/vqsort-inl.h
hwy/contrib/unroller/unroller-inl.h
hwy/ops/emu128-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h

Added a new 3-argument CopyBytes function in hwy/base.h that takes an additional num_of_bytes_to_copy argument.
Also replaced `memcpy(to, from, N)` calls with `CopyBytes(from, to, N)` calls (where `N` is the number of bytes to copy) in hwy/contrib/sort/algo-inl.h, hwy/contrib/sort/vqsort-inl.h, hwy/contrib/unroller/unroller-inl.h, hwy/ops/emu128-inl.h, 
hwy/ops/x86_128-inl.h, and hwy/ops/x86_256-inl.h.

Replaced memcpy with 3-argument CopyBytes

---

hwy/tests/arithmetic_test.cc

Updated UI64 ScalarAbsDiff in TestIntegerAbsDiff to cast its operands to uint64_t before subtraction as subtraction overflow in int64_t ScalarAbsDiff is possible on the RVV target if `Lanes(ScalableTag<int64_t>()) >= 8` is true (which implies that `Lanes(ScalableTag<int64_t, 3>()) >= 64` is true on the RVV target).

Fixed UI64 ScalarAbsDiff in TestIntegerAbsDiff

---

hwy/ops/set_macros-inl.h

This reverts commits 60241b99 and f8a6ea58.
GCC understands (like Clang) appending an architecture extension on its own. This can be used to turn on and off particular architectural extensions without having to specify a particular architecture version or core.
GCC supports this since at least 6.5. Check:
https://gcc.gnu.org/onlinedocs/gcc-6.5.0/gcc/AArch64-Function-Attributes.html
https://gcc.gnu.org/onlinedocs/gcc/AArch64-Function-Attributes.html
This way we can enable the crypto architecture extension for `HWY_NEON` without overriding the default architecture of the compiler potentially disabling other architectural extensions.
This fixes a build error that happens with the RPi4 and a Yocto-based toolchain that by default builds with `-march=armv8-a+crc` (the RPi4 has no crypto arch …

HWY_NEON: Enable the crypto extension for GCC without setting the full arch

---

hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/scalar-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/tests/if_test.cc

Made the following bug fixes to IfNegativeThenElse:
- Updated SSE2/SSSE3 implementations to broadcast the sign bit
- Updated EMU128/SCALAR implementations to use `vi` (which is `v` bitcasted to `Vec<RebindToSigned<DFromV<decltype(v)>>>`) to match the behavior of x86/NEON/PPC IfNegativeThenElse
Made the following enhancements to IfNegativeThenElse:
- Updated RVV/SVE IfNegativeThenElse to avoid broadcasting the sign bit and simply do a signed integer less-than comparison (as RVV/SVE MaskFromVec simply does a comparison against zero)
- Updated PPC10 IfNegativeThenElse to do a vec_blend (which has the same behavior as SSE4 _mm_blendv_epi8, _mm_blendv_ps, and _mm_blend_pd)
Also updated TestIfNegative to add additional checks that would expose the bugs that were previously there with the …

Made fixes and enhancements to IfNegativeThenElse

---

g3doc/quick_reference.md
hwy/ops/emu128-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/scalar-inl.h
hwy/ops/x86_128-inl.h
hwy/tests/memory_test.cc

Added the LoadN operation to allow only the first (lowest-indexed) `HWY_MIN(Lanes(d), max_lanes_to_load)` lanes to be loaded without faulting.
Also added the StoreN operation to allow only the first (lowest-indexed) `HWY_MIN(Lanes(d), max_lanes_to_store)` lanes to be stored without faulting or modifying any memory past `p + HWY_MIN(Lanes(d), max_lanes_to_store) - 1`.

Added LoadN and StoreN operations

---

g3doc/quick_reference.md
hwy/ops/generic_ops-inl.h
hwy/ops/scalar-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/mul_test.cc

Added U8xI8 SatWidenMulPairwiseAdd operation, which is a saturated pairwise sum of two adjacent U8xI8 products.
SSSE3/SSE4/AVX2/AVX3 can do an U8xI8 SatWidenMulPairwiseAdd operation using a single pmaddubsw instruction.

Added SatWidenMulPairwiseAdd

---

hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h

Fix compilation errors with x86 Load/Store when compiled with GCC 10.
Also fixed AVX2/AVX3 F16 LoadU operation to invoke the U16 LoadU operation instead of the U16 Load operation.

Fix GCC10 compilation errors with x86 Load/Store operations

---

hwy/ops/emu128-inl.h
hwy/ops/scalar-inl.h
hwy/tests/mul_test.cc

Updated EMU128/SCALAR MulFixedPoint15 to compute `(a[i] * b[i] + 16384) >> 15` instead of `(2 * a[i] * b[i] + 32768) >> 16` to avoid overflow in the case where `a[i]` and `b[i]` are both equal to -32768.
Also changed `2 * in1[i] * in2[i] + 0x8000` to `static_cast<int32_t>(2u * static_cast<uint32_t>(in1[i] * in2[i]) + 0x8000u)` in TestMulFixedPoint15 to avoid undefined behavior in the case where `in1[i]` and `in2[i]` are both equal to -32768.

Made fixes to TestMulFixedPoint15 and EMU128/SCALAR MulFixedPoint15

---

g3doc/op_wishlist.md
g3doc/quick_reference.md
hwy/ops/generic_ops-inl.h
hwy/tests/mask_mem_test.cc

Both `ScatterIndexN`/`GatherIndexN` are simply wrappers around `MaskedGatherIndex`/`MaskedScatterIndex`, using FirstN to only collect up to N values.
These interfaces can be updated later with platform-specific optimisations.

Add GatherIndexN/ScatterIndexN operations

---

hwy/base.h

Updated hwy/base.h to fix compilation issue on i686 target with SSE2 disabled.
Resolves issue #1663.

Fixed compilation issue on i686 target

---

hwy/ops/ppc_vsx-inl.h

Made the following enhancements to the Compress and Expand operations on PPC9/PPC10:
- Added detail::CompressOrExpandIndicesFromMask on the HWY_PPC10 target, which is a wrapper around the PPC10 xxgenpcvbm/xxgenpcvhm/xxgenpcvwm instructions
- Reimplemented I8/U8 Compress on PPC10 to do a TableLookupBytes using indices returned by detail::CompressOrExpandIndicesFromMask
- Updated CompressBlendedStore implementations in hwy/ops/ppc_vsx-inl.h to use StoreN on PPC9/PPC10 instead of BlendedStore as StoreN is more efficient than BlendedStore on PPC9/PPC10
- Reimplemented Expand on HWY_PPC10 target to use TableLookupBytes using indices returned by detail::CompressOrExpandIndicesFromMask for vectors that have 1-byte, 2-byte, or 4-byte lanes

Made enhancements to Compress and Expand operations on PPC9/PPC10

---

README.md

Update the amount of supported architectures now that PowerPC is supported. 
Also, avoid stating how many instruction sets are supported to prevent the need of changes in this text.

Docs: update amount of supported architectures

---

hwy/ops/wasm_128-inl.h

Added implementation of detail::ExtractLane for BF16/F16 vectors in hwy/ops/wasm_128-inl.h to fix compilation errors on WASM.

Fixed WASM ExtractLane for BF16/F16 vectors

---

hwy/base.h

Fixed `operator--` and `operator++` for hwy::float16_t and hwy::bfloat16_t.
The post-increment operator (`x++`) and the post-decrement operator (`x--`) are supposed to return the value prior to the increment or decrement instead of the value after the increment. Fixed the post-increment operator and post-decrement operator to match the expected behavior.
Also updated the pre-increment operator (`++x`) and pre-decrement operator (`--x`) to return a reference to `*this` as the pre-increment operator and pre-decrement operators are expected to return a reference to `*this`.
Post-increment, post-decrement, pre-increment, and pre-decrement operators are explained at https://en.cppreference.com/w/cpp/language/operator_incdec.

Added fixes for float16_t/bfloat16_t operator++ and operator--

---

hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h

Resolves issue #1711.
Replaced _knot_mask8 and _knot_mask16 with detail::UnmaskedNot or Not.

Fix AVX3 mask compilation issues

---

hwy/base.h
hwy/ops/emu128-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/rvv-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/x86_128-inl.h
hwy/tests/convert_test.cc

Added BitCastScalar operation, which bit casts `val` to `To`.
Also added `HWY_BITCASTSCALAR_CONSTEXPR` macro, which expands to the `constexpr` keyword if the current compiler supports `__builtin_bit_cast` and is defined as an empty macro otherwise.

Added BitCastScalar operation

---

hwy/base.h
hwy/base_test.cc
hwy/ops/shared-inl.h

Added the following type traits:
- `IsInteger<T>()` - returns true if `T` is one of the following types and returns false otherwise:
`bool`, `char`, `signed char`, `unsigned char`, `short`, `unsigned short`, `int`, `unsigned int`, `long`, `unsigned long`, `long long`, `unsigned long long`, `int8_t`, `uint8_t`, `int16_t`, `uint16_t`, `int32_t`, `uint32_t`, `int64_t`, `uint64_t`, `char8_t`, `char16_t`, `char32_t`, `wchar_t`, `intptr_t`, `uintptr_t`, `size_t`, `ptrdiff_t`
- `IsIntegerLaneType<T>()` - returns true if `T` is one of the following types and returns false otherwise:
`int8_t`, `uint8_t`, `int16_t`, `uint16_t`, `int32_t`, `uint32_t`, `int64_t`, `uint64_t`
- `RemoveVolatile<T>` - removes the `volatile` qualifier off of `T`
- `RemoveCvRef<T>` - equivalent to …

Added IsInteger, IsIntegerLaneType, RemoveVolatile, and RemoveCvRef

---

hwy/contrib/sort/algo-inl.h

At the moment, algo-inl.h pulls in the test util header which in turn depends on the Google Test library. It seems however that only aligned allocator support is required. Narrow the include to permit using this header in contexts which do not form part of testing, or where a dependency on Google Test is not desired.

Narrow include in algo-inl.h

---

g3doc/quick_reference.md
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/rvv-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/combine_test.cc

Added the InterleaveWholeLower and InterleaveWholeUpper operations, which operate on the whole lower halves or whole upper halves of the vectors.
Resolves issue #1756.

Added InterleaveWholeLower and InterleaveWholeUpper ops

---

hwy/ops/arm_sve-inl.h
hwy/tests/convert_test.cc

Fixed SVE F32->U64 PromoteEvenTo implementation to call svcvt_u64_f32_x instead of svcvt_s64_f32_x.
Also updated TestPromoteOddEvenTo to test F32->I64 and F32->U64 PromoteEvenTo/PromoteOddTo.

Fixes to SVE F32->U64 PromoteEvenTo and TestPromoteOddEvenTo

---

hwy/base.h

Changed the type of the third parameter of hwy::AddWithWraparound from `size_t` to `T2` to fix compilation warnings in TestSumOfLanes in hwy/tests/reduction_test.cc.

Updated AddWithWraparound to fix warnings in reduction_test

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/scalar-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/tests/convert_test.cc
hwy/tests/reduction_test.cc
hwy/tests/test_util.h

Added the SumsOf2 and SumsOf4 operations.
Also added the SumsOf8 and SumsOf8AbsDiff operations for I8 vectors.
Also updated the N=4 I8/U8 ReduceSum/ReduceMin/ReduceMax operations in generic_ops-inl.h to allow for target-specific optimized implementations of the N=4 I8/U8 ReduceSum/ReduceMin/ReduceMax operations.
Updated the N=4 I8/U8 ReduceSum implementation on PPC8/PPC9/PPC10/Armv7 Neon to do a `GetLane(SumsOf4(v))` instead of the default implementation in generic_ops-inl.h as `GetLane(SumsOf4(v))` is more efficient than the default implementation in generic_ops-inl.h for N=4 I8/U8 vectors on PPC8/PPC9/PPC10/Armv7 Neon.
Also updated implementations of ReduceSum/ReduceMin/ReduceMax on RVV/SVE to use the ReduceSum/ReduceMin/ReduceMax implementations in arm_sve-inl.h or rvv-inl.h for N=4 …

Added SumsOf2/SumsOf4/I8 SumsOf8 plus enhancements to reduce ops

---

hwy/ops/generic_ops-inl.h
hwy/tests/reduction_test.cc

Updated I8/U8 implementation of SumsOf8AbsDiff in generic_ops-inl.h to fix a bug with I8 SumsOf8AbsDiff as the result of the I8 AbsDiff operation needs to be bitcasted to an U8 vector.
Also enabled TestSumsOf8AbsDiff for int8_t vectors that are >= 64 bits.

Made fixes to I8 SumsOf8AbsDiff

---

hwy/ops/x86_512-inl.h

Fixes compilation error:
hwy/ops/x86_512-inl.h: In function 'hwy::N_AVX3::MFromD<D> hwy::N_AVX3::FirstN(D, size_t)': hwy/ops/x86_512-inl.h:755:25: error: 'T' was not declared in this scope
755 |   return detail::FirstN<T>(n);
|                         ^

Fix compilation on x86+AVX2

---

g3doc/quick_reference.md
hwy/ops/generic_ops-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/reduction_test.cc

Resolves issue #1779.
SumsOfAdjQuadAbsDiff is a wrapper around _mm_mpsadbw_epu8/_mm256_mpsadbw_epu8 on SSE4/AVX2/AVX3 for U8 vectors that are 32 bytes or smaller.
SumsOfAdjShufQuadAbsDiff is a wrapper around _mm_dbsad_epu8/_mm256_dbsad_epu8/_mm512_dbsad_epu8 for U8 vectors on SSE4/AVX2/AVX3. SumsOfAdjShufQuadAbsDiff is also used to implement SumsOfAdjQuadAbsDiff for 64-byte U8 vectors on AVX3.

Added SumsOfAdjQuadAbsDiff and SumsOfShuffledQuadAbsDiff ops

---

hwy/base.h
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h

Added hwy::DeclVal&lt;T&gt;(), which is intended to be used in the same use cases as std::declval&lt;T&gt;().
Also added hwy::IsArray&lt;T&gt;(), hwy::IsConvertible&lt;From, To&gt;(), hwy::IsStaticCastable&lt;From, To&gt;(), and hwy::IsAssignable&lt;T, From&gt;() as they are used to selectively enable constructors and arithmetic assignment operators in the updated hwy::float16_t and hwy::bfloat16_t implementations.
Also disabled ARM __bf16 type with Clang 16 or earlier as there are compilation errors with __bf16 with Clang 16 or earlier.
Enabled the use of __bf16 on AArch64 with GCC 11 or later as __bf16 is supported on AArch64 with GCC 11 or later and as GCC 11 and later has support for the SVE svbfloat16_t vector type.
Also enabled the use of __bf16 on x86 with GCC 13 or later if SSE2 …

Made fixes to hwy::float16_t and hwy::bfloat16_t

---

hwy/ops/generic_ops-inl.h

Updated IsInf implementation in generic_ops-inl.h to cast MaxExponentField&lt;T&gt;() to MakeUnsigned&lt;T&gt; to fix compilation errors.

Updated IsInf implementation in generic_ops-inl.h

---

hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h

Made the following enhancements to x86 Abs:
- Made F16/F32/F64 Abs generic for all vector lengths on SSE2/SSSE3/SSE4/AVX2/AVX3
- Made I64 Abs generic for all vector lengths on SSE2/SSSE3/SSE4/AVX2
- Reimplemented SSE2/SSSE3/SSE4/AVX2 I64 Abs to use IfNegativeThenElse

Made enhancements to x86 F16/F32/F64/I64 Abs

---

BUILD
CMakeLists.txt
g3doc/quick_reference.md
hwy/base.h
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/scalar-inl.h
hwy/ops/shared-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/mask_combine_test.cc
hwy/tests/mask_convert_test.cc
hwy/tests/mask_test.cc

Added the following mask operations:
- Dup128MaskFromMaskBits - creates a mask from mask bits, broadcasted to each 16-byte block if `d.MaxBytes() > 16` is true
- PromoteMaskTo - promotes a mask to a mask with a larger lane type
- DemoteMaskTo - demotes a mask to a mask with a smaller lane type
- OrderedDemote2MasksTo - demotes two masks to a single mask with a smaller lane type
- CombineMask - combines two masks
- LowerHalfOfMask - returns lower half of a mask
- UpperHalfOfMask - returns upper half of a mask

Added additional mask conversion/combine/split/creation ops

---

.github/workflows/build_test.yml

Here is an updated version of .github/workflows/build_test.yml that adds Clang 13/14/15 and GCC 11/12 to the Build/Test workflow.
The clang-13, clang-14, clang-15, g++-11, and g++-12 Build/Test steps require Ubuntu 22.04 as the clang-13, clang-14, clang-15, g++-11, and g++-12 packages are not available in the Ubuntu 20.04 repository.
Still need to use Ubuntu 20.04 to compile with Clang 6/7/8/9/10 and GCC 8 as Ubuntu 22.04 has removed the Clang 6/7/8/9/10 and GCC 8 packages.
It is possible to update .github/workflows/build_test.yml to have the Clang 11/12 and GCC 9/10 build/test steps to use Ubuntu 22.04 instead of Ubuntu 20.04.
Is it too much to add the extra Clang/GCC compilers that are available in Ubuntu 22.04 to the GitHub workflow?

Add Clang 13/14/15 and GCC 11/12 to GitHub workflow

---

BUILD
CMakeLists.txt
g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/scalar-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/dup128_vec_test.cc

Resolves issue #1706
Dup128VecFromValues was added as Dup128FromValues is more efficient than LoadDup128 on some targets.

Added Dup128VecFromValues operation

---

hwy/ops/arm_sve-inl.h

Added missing detail::LoadDupFull128 for BF16 vectors to hwy/ops/arm_sve-inl.h if HWY_SVE_HAVE_BFLOAT16 is 1.

Fix SVE LoadDup128 compilation error if HWY_SVE_HAVE_BFLOAT16 is 1

---

hwy/base.h
hwy/ops/arm_neon-inl.h
hwy/ops/ppc_vsx-inl.h

In some case we know it is acceptable to increase alignement. Hint the compiler when doing so.
Solve typical warning messages:
highway/hwy/ops/ppc_vsx-inl.h:619:35: error: cast from 'const long unsigned int* __restrict__' to 'const LoadRaw*' {aka 'const __vector(2) long unsigned int*'} increases required alignment of target type [-Werror=cast-align]
619 |   const LoadRaw* HWY_RESTRICT p = reinterpret_cast<const LoadRaw*>(aligned);
|                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Introduce a macro for reinterpret_cast special case

---

CMakeLists.txt

This is needed for x86_32 or s390x where gnu extensions defaults to `-fexcess-precision=fast` while highway/math wants `-fexcess-precision=standard`
References:
* https://bugs.debian.org/1053641
And
* https://cmake.org/cmake/help/latest/policy/CMP0128.html#policy:CMP0128

Remove GNU extension from compilation

---

g3doc/quick_reference.md
hwy/ops/generic_ops-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/if_test.cc

The CondNegateOrZero operation was added as SSSE3/SSE4/AVX2/AVX3 have PSIGNB/PSIGNW/PSIGND instructions that can carry out the `IfNegativeThenElse(b, Neg(a), IfThenZeroElse(Eq(b, Zero(d)), a))` operation for I8/I16/I32 vectors that are 32 bytes or smaller.
AVX3 can also more efficiently carry out the `b[i] < 0 ? (-a[i]) : (a[i])` operation for I8/I16/I32/I64 vectors using `MaskedSubOr(a, MaskFromVec(b), Zero(d), a)`.

Added IfNegativeThenNegOrUndefIfZero operation

---

hwy/contrib/algo/copy-inl.h
hwy/contrib/algo/find-inl.h
hwy/contrib/algo/transform-inl.h

Replaced `idx + N <= count` with  `idx <= count - N` in copy-inl.h, find-inl.h, transform-inl.h in hwy/contrib/algo as it is possible for `idx + N` to overflow if `idx > LimitsMax<size_t>() - N` is true, whereas `idx <= count - N` is guaranteed to not overflow if `count >= N` is true.
Also added `if (count >= N)` checks to ensure that the `for (; idx <= count - N; idx += N)` loops in copy-inl.h, find-inl.h, transform-inl.h are only executed if `count >= N` is true.
The changes to the loops in copy-inl.h, find-inl.h, and transform-inl.h also work around `-Waggressive-loop-optimizations` warnings that were encountered when compiling hwy/contrib/matvec/matvec_test.cc on PPC with GCC.

Made fixes to loops in hwy/contrib/algo/copy-inl.h, find-inl.h, and transform-inl.h

---

hwy/contrib/matvec/matvec-inl.h

Remove unused VF typedef in hwy/contrib/matvec/matvec-inl.h to fix compilation errors in build/test

Fixed compilation error in hwy/contrib/matvec/matvec-inl.h

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/x86_128-inl.h
hwy/tests/arithmetic_test.cc

Added SaturatedAbs and SaturatedNeg operation as NEON/SVE2 have instructions for the SaturatedAbs and SaturatedNeg operations.
`SaturatedNeg(a)` is also more efficient than `SaturatedSub(Zero(d), a)` for I32/I64 vectors on some targets.
`SaturatedNeg(a)` is also usually more efficient than `IfThenElse(Eq(a, Set(d, LimitsMin<TFromD<D>>())), Set(d, LimitsMax<TFromD<D>>()), Neg(a))`.
`SaturatedAbs(a)` is also more efficient than `Max(a, SaturatedSub(Zero(d), a))`, `IfThenElse(Eq(a, Set(d, LimitsMin<TFromD<D>>())), Set(d, LimitsMax<TFromD<D>>()), Abs(a))`, or `Min(BitCast(du, Abs(a)), Set(du, LimitsMax<T>()))` on some targets.

Added SaturatedAbs and SaturatedNeg operations

---

hwy/ops/scalar-inl.h

Replaced `Vec1<T>(0)` with `Vec1<T>(ConvertScalarTo<T>(0))` in the IfThenElseZero, IfThenZeroElse, and ZeroIfNegative implementations in hwy/ops/scalar-inl.h to fix compilation errors with HWY_SCALAR target.
Also updated Zero function in hwy/ops/scalar-inl.h to return `Vec1<T>(ConvertScalarTo<T>(0))`.

Fix compilation errors with HWY_SCALAR target

---

hwy/base.h

Updated BitCastScalar to allow constexpr bit casts from hwy::float16_t and hwy::bfloat16_t if the __builtin_bit_cast intrinsic is available and To is either (a) a floating-point type (including hwy::float16_t and hwy::bfloat16_t), (b) an integer type, or (c) a class or struct type that does not contain any union, pointer, reference, or volatile-qualified subobjects.
Also updated BitCastScalar to allow constexpr bit casts to hwy::float16_t or hwy::bfloat16_t from integer types, floating-point types, or class/struct types that do not contain any union, pointer, reference, or volatile-qualified subobjects if the __builtin_bit_cast intrinsic is available.
Also added a hwy::float16_t::FromBits static member function that bit casts a uint16_t to hwy::float16_t, and also added a …

Made enhancements to BitCastScalar and fixed F16 compare operators

---

hwy/tests/sums_abs_diff_test.cc

Fixed Clang compiler warning in TestSumsOfAdjQuadAbsDiff by casting result of ScalarAbs to TW_I.

Fixed Clang compiler warning in TestSumsOfAdjQuadAbsDiff

---

hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h

Fixes compile errors for F16 Load/LoadU/Store/StoreU on AVX2/AVX3 with GCC

GCC AVX2/AVX3 compilation fixes for F16 Load/Store

---

hwy/ops/arm_neon-inl.h
hwy/ops/emu128-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/scalar-inl.h
hwy/tests/convert_test.cc

Updated SCALAR/EMU128 F->UI PromoteTo/ConvertTo/DemoteTo to ensure that undefined behavior does not occur if the source vector contains any NaN values.
On PPC8/PPC9/PPC10, also updated F->UI PromoteTo/ConvertTo/DemoteTo operations that use VSX F->UI conversion instructions to zero out any NaN source values unless HWY_DISABLE_PPC_VSX_QEMU_F2I_WORKAROUND is defined to work around a bug in QEMU 7/8 where a NaN value in the source floating-point vector can cause subsequent lanes to be incorrectly converted to an integer.
Also updated NEON F->UI PromoteTo/ConvertTo/DemoteTo operations to use inline assembly when compiled for ArmV7 with Clang or when compiled for AArch64 with Clang 11 or earlier to avoid undefined behavior if any of the source values are outside of the range of the result type.

Made fixes to SCALAR, EMU128, NEON, and PPC float to int conversions

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/scalar-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/arithmetic_test.cc

Added Div/Mod operations for integer vectors
Resolves issue #633
RVV/SVE/PPC10 have native vector integer division instructions. Other targets implement integer vector division using floating-point division.
For integer vectors, `Div(a, b)` is only guaranteed to return `a[i] / b[i]` if `b[i] != 0 && (!IsSigned<T>() || a[i] != LimitsMin<T>() || b[i] != -1)` is true.
For integer vectors, `Mod(a, b)` is only guaranteed to return `a[i] % b[i]` if `b[i] != 0 && (!IsSigned<T>() || a[i] != LimitsMin<T>() || b[i] != -1)` is true.

Added integer Div/Mod operations

---

hwy/ops/generic_ops-inl.h

Fixed endianness bug in U16/I16/F16/BF16 Expand implementation in generic_ops-inl.h.
The U16/I16/F16/BF16 Expand implementation in generic_ops-inl.h now has correct behavior on both big-endian targets and little-endian targets with the fix in this pull request.

Fixed endianness bug in U16/I16/F16/BF16 Expand in generic_ops-inl.h

---

hwy/ops/emu128-inl.h

Updated `InterleaveLower(D, VFromD<D>, VFromD<D>)` overload in hwy/ops/emu128-inl.h to fix compilation errors in the case where `D().Pow2() != 0` is true.

Fixed EMU128 InterleaveLower with D parameter

---

hwy/base.h
hwy/ops/set_macros-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/float_test.cc

This pull request enables F16 support on the AVX3_SPR target when compiled with GCC.
This pull request also includes fixes to some of the operations in x86_128-inl.h, x86_256-inl.h, and x86_512-inl.h to allow the AVX3_SPR target to successfully compile with F16 support enabled.
There is still a compilation warning in hwy/tests/reduction_test.cc that needs to be fixed when AVX3_SPR is compiled with F16 support enabled.
All of the Highway unit tests pass on the AVX3_SPR target with F16 support enabled with the changes in this pull request when compiled with GCC 13.2.0.

Enable F16 for AVX3_SPR when compiled with GCC

---

hwy/ops/wasm_256-inl.h

Updated operator / in wasm_256-inl.h to fix compilation error for 256-bit integer vectors.

Fix operator / in wasm_256-inl.h

---

hwy/ops/ppc_vsx-inl.h

Replaced hwy::CopySameSize with BitCastScalar in PPC InsertLane op to fix compilation error.

Fixed PPC InsertLane

---

hwy/ops/ppc_vsx-inl.h

Fixes to PPC10 Div/Mod inline assembly to fix compilation errors with Clang

Fix PPC10 Div/Mod inline assembly

---

hwy/tests/list_targets.cc

Updated PrintTargets in list_targets.cc to avoid undefined behavior if the the parameter has the sign bit set as it is possible for HWY_BROKEN_TARGETS and HWY_DISABLED_TARGETS to have the sign bit set if the HWY_BROKEN_TARGETS or HWY_DISABLED_TARGETS macros are defined by the user prior to including hwy/highway.h.

Fixed PrintTargets in list_targets.cc

---

g3doc/quick_reference.md
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/rvv-inl.h
hwy/ops/x86_128-inl.h
hwy/tests/mask_test.cc
hwy/tests/test_util-inl.h

This pull request makes the `MaskFalse(d)` op available to non-test code on all targets.
Also reimplemented the `MaskFalse(d)` op on targets other than RVV.
Also added the TestAllMaskFalse test that checks that all of the bits of `MaskFalse(d)` are false, including any bits past the first `Lanes(d)` lanes of `MaskFalse(d)`.

Make MaskFalse available to non-test code on all targets

---

hwy/tests/arithmetic_test.cc

Reformatted TestIntegerDiv in hwy/tests/arithmetic_test.cc using clang-format

Reformatted TestIntegerDiv in arithmetic_test.cc

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/emu128-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/scalar-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/arithmetic_test.cc
hwy/tests/mul_test.cc

Added the AddSub and MulAddSub operations for both integer and floating point vectors.
The AddSub operation returns `a[i] - b[i]` in the even lanes and `a[i] + b[i]` in the odd lanes.
The MulAddSub operation returns `mul[i] * x[i] - sub_or_add[i]` in the even lanes and `mul[i] * x[i] + sub_or_add[i]` in the odd lanes.
Also added the MulSub and NegMulSub ops for integer vectors.

Added AddSub, MulAddSub, integer MulSub, and integer NegMulSub ops

---

hwy/base.h
hwy/ops/set_macros-inl.h

This pull request fixes compilation errors on x86_64 with pre-release versions of Clang 15.
Support for _Float16 on SSE2/SSSE3/SSE4/AVX2 was added to Clang in LLVM revision [abeeae570efff38dceccf68f5352809c58ffdda2](https://github.com/llvm/llvm-project/commit/abeeae570efff38dceccf68f5352809c58ffdda2), which was integrated into the final Clang 15.0.0 release.
Both GCC and Clang define the `__FLT16_MAX__` macro if the `_Float16` type is available. The addition of the `defined(__FLT16_MAX__)` check in this pull request should prevent compilation errors with pre-release versions of Clang 15.

Fix for x86 _Float16 compilation errors with Clang 15

---

g3doc/quick_reference.md
hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/scalar-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/convert_test.cc

Added F64->F16 DemoteTo op as AVX3_SPR/PPC9/PPC10/SVE have F64->F16 demotion instructions and to ensure that the F64->F16 demotion is correctly rounded on all targets as simply doing a `DemoteTo(df16, DemoteTo(Rebind<float, decltype(df16)>(), v))` might result in an incorrectly rounded value.
Added F16->F64 PromoteTo op as AVX3_SPR/SVE have instructions for F16->F64 promotion.

Added F16->F64 PromoteTo and F64->F16 DemoteTo ops

---

hwy/contrib/unroller/unroller_test.cc

Updated FindUnit constructor in unroller_test.cc, which fixes compilation errors with GCC 11 in C++20 mode.

Fix FindUnit constructor in unroller_test.cc

---

hwy/targets.cc

The following OS's are known to preserve the lower 128 bits of XMM registers across context switches on x86 CPU's with SSE support, even in 32-bit mode:
- Windows 2000 (released on 2/17/2000) or later
- Linux 2.4.0 (released on 1/4/2001) or later
- FreeBSD 4.4 (released on 9/20/2001) or later
- NetBSD 1.6 (released on  9/14/2002) or later
- OpenBSD 3.5 (released on 5/1/2004) or later
- Mac OS X 10.4.4 (released on 1/10/2006) or later
- Solaris 9 4/04 (released in 2004) or later
- UnixWare 7 Release 7.1.1 (released in 2000) or later
The lower 128 bits of XMM0-XMM15 are guaranteed to be preserved across context switches on x86_64, even on x86_64 CPU's that don't support the XSAVE instruction.
Updated x86 DetectTargets() to only clear the AVX2/AVX3 bits if the CPU or OS doesn't support XSAVE …

Fixes to x86 target detection

---

g3doc/quick_reference.md

Corrected the description of the HWY_IS_BIG_ENDIAN macro in g3doc/quick_reference.md

Corrected documentation of HWY_IS_BIG_ENDIAN macro

---

hwy/ops/rvv-inl.h

Fixed compiler errors in RVV debug builds.
Also fixed bug in Broadcast op in hwy/ops/rvv-inl.h for I8/U8 vectors with LMUL=8.

Fixes to RVV Broadcast

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/scalar-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/shift_test.cc

Added the Rol, Ror, RotateLeft, RotateLeftSame, and RotateRightSame ops.
The Rol and Ror ops were added as AVX3 has per-lane variable rotate left/rotate right instructions for U32/U64 vectors and as PPC has per-lane variable rotate left instructions for U8/U16/U32/U64 vectors.
The `RotateLeft<kBits>(v)` op is simply a wrapper around `RotateRight<(kBits == 0 ? 0 : (sizeof(TFromV<V>)*8-kBits))>(v)`.
Also updated AVX3_DL U8 RotateRight to use detail::GaloisAffine.
Also updated RotateRight on SVE2 to use svxar_n_u8/16/32/64.
Also changed the `bits` parameter of ShiftLeftSame/ShiftRightSame in hwy/ops/arm_sve-inl.h to `int` to fix compiler warnings in RotateLeftSame and RotateRightSame on SVE.

Added Rol, Ror, RotateLeft, RotateLeftSame, and RotateRightSame ops

---

CMakeLists.txt
hwy/contrib/bit_pack/bit_pack_test.cc

Add the corresponding test as well.
Test with `run_tests.bat`
Verify with `cmake --install . --prefix=install` in the build_win directory.
Fix warnings as errors for gcc and clang using explicit casts.
#2011

Add bit_pack-inl.h to CMakeLists.txt

---

CMakeLists.txt

Some warnings were not detected when making changes on a Windows development machine.
These were detected later during the CI tests for the pull request.
These changes makes warnings easier to detect in the development process.
#2011

Enable warnings as errors for cl.exe and clang-cl on Windows.

---

hwy/ops/scalar-inl.h

Replaced remaining usages of isnan with ScalarIsNaN in scalar-inl.h.

Replaced remaining usages of isnan with ScalarIsNaN in scalar-inl.h

---

g3doc/quick_reference.md
hwy/highway_test.cc
hwy/ops/generic_ops-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h

Added IsEitherNaN op as SSE2/SSSE3/SSE4/AVX2/AVX3 can carry out `Or(IsNaN(a), IsNaN(b))` using a single VCMPPH/(V)CMPPS/(V)CMPPD instruction.

Added IsEitherNaN op

---

g3doc/quick_reference.md
hwy/base.h
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/scalar-inl.h
hwy/ops/shared-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/compare_test.cc
hwy/tests/if_test.cc

Added IsNegative op as `Lt(v, Zero(d))` is more efficient than `MaskFromVec(BroadcastSignBit(v))` on some targets whereas `MaskFromVec(BroadcastSignBit(v))` is more efficient than `Lt(v, Zero(d))` on some other targets.
Also added IfNegativeThenElseZero op as `IfThenElseZero(IsNegative(v), yes)` is more efficient than `IfNegativeThenElse(v, yes, Zero(d))` on some targets whereas `IfNegativeThenElse(v, yes, Zero(d))` is more efficient than `IfThenElseZero(IsNegative(v), yes)` on some other targets.
Also added IfNegativeThenZeroElse op as `IfThenZeroElse(IsNegative(v), no)` is more efficient than `IfNegativeThenElse(v, Zero(d), no)` on some targets whereas `IfNegativeThenElse(v, Zero(d), no)` is more efficient than `IfThenZeroElse(IsNegative(v), no)` on some other targets.
Also moved …

Added IsNegative, IfNegativeThenElseZero, and IfNegativeThenZeroElse ops

---

README.md

Mention in `README.md` that sometimes MSVC would generate VEX-encoded SSE, but not always

---

g3doc/quick_reference.md
hwy/base.h
hwy/base_test.cc
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/scalar-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/mul_test.cc

Added I8/U8/I32/U32/I64/U64 MulHigh and I64 MulEven/MulOdd/Mul128 ops.
RVV/SVE/Z14 have instructions for I8/U8 MulHigh, RVV/SVE/PPC10/Z14 have instructions for I32/U32 MulHigh, and RVV/SVE/PPC10 have instructions for I64/U64 MulHigh.

Added UI8/UI32/UI64 MulHigh and I64 MulEven/MulOdd/Mul128

---

hwy/contrib/matvec/matvec-inl.h

Added `(void)add` to MatVecAddImpl to work around a compilation warning with GCC 8 in C++17 mode if `kAdd` is false.

Fix for compilation error in matvec-inl.h with GCC 8 in C++17 mode

---

hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/scalar-inl.h
hwy/ops/shared-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h

Unsigned to signed DemoteTo/ReorderDemote2To on EMU128/SCALAR/SVE/SVE2 now use target-specific implementations
Also updated U64->I8/I16/I32 DemoteTo/ReorderDemote2To to use target-specific implementations on SSE2/SSSE3/SSE4/AVX2

Made enhancements to unsigned to signed DemoteTo/ReorderDemote2To

---

hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/shared-inl.h
hwy/ops/x86_128-inl.h

SVE has instructions that can do the `AddSub(a, Reverse2(DFromV<decltype(b)>(), b))` op for floating-point vectors.
SVE2 also has instructions that can do the  `AddSub(a, Reverse2(DFromV<decltype(b)>(), b))` op for integer vectors.
This pull request re-implements F16/F32/F64 AddSub on SVE using `svcadd_f*_x(HWY_SVE_PTRUE(BITS), a, Reverse2(d, b), 90)` and re-implements integer AddSub on SVE2 using `svcadd_s*(a, Reverse2(d, b), 90)` and `svcadd_u*(a, Reverse2(d, b), 90)`.
Also reimplemented F16/F32/F64 MulAddSub on SVE to negate the even lanes of `sub_or_add` using `AddSub(Set(d, neg_zero), sub_or_add)`, where `neg_zero` is equal to `ConvertScalarTo<T>(-0.0f)`. Negating the even lanes of `sub_or_add` using `-0.0 - sub_or_add[i]` ensures that positive zero values in even lanes are negated …

Reimplemented AddSub and MulAddSub on SVE/SVE2

---

hwy/ops/arm_neon-inl.h
hwy/ops/set_macros-inl.h

Currently `__ARM_VFPV4__` is used, which I can't see defined in GCC, though `__ARM_FEATURE_FMA` is available: https://github.com/gcc-mirror/gcc/blob/97d5cd8740384dbce5a83080916388f80d8976dd/gcc/config/arm/arm-c.cc#L361C31-L361C48 And is targetting the same as `__ARM_VFPV4__`:
https://github.com/gcc-mirror/gcc/blob/97d5cd8740384dbce5a83080916388f80d8976dd/gcc/config/arm/arm.h#L211

Use __ARM_FEATURE_FMA to detect FMA support

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/scalar-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/widen_mul_test.cc

Resolves issue #2050
The `SatWidenMulPairwiseAccumulate(DI32, VI16 a, VI16 b, VI32 sum)` op was added as AVX3_DL/PPC8/PPC9/PPC10 can carry out the `SatWidenMulPairwiseAccumulate(di32, a, b, sum)` op using a single instruction.
Adding the SatWidenMulPairwiseAccumulate op also allows the `SatWidenMulAccumFixedPoint(di32, a, b, sum)` op to be more efficiently implemented for x86 and PPC targets.
On NEON, `SatWidenMulAccumFixedPoint(di32, a, b, sum)` is a wrapper around the NEON vqdmlal_s16 op.
Similarly, on SVE2, `SatWidenMulAccumFixedPoint(di32, a, b, sum)` is a wrapper around the SVE2 svqdmlalb_s32 op.

Added SatWidenMulPairwiseAccumulate and SatWidenMulAccumFixedPoint ops

---

hwy/ops/generic_ops-inl.h

Whilst benchmarking https://github.com/numpy/numpy/pull/25781 I realised these were not translated well by the compiler. These implementations make the compiler work less by explicitly using `ExtractLane` and `InsertLane`.
With these, the NumPy benchmarks show `sin`/`cos` not regressing on AArch64 after migrating to Highway :smile_cat:

Improve generic implementations of GatherIndexN and ScatterIndexN

---

hwy/base.h
hwy/ops/generic_ops-inl.h
hwy/tests/demote_test.cc

Fixed the F32 to F16 DemoteTo implementation in generic_ops-inl.h to prevent out-of-range finite values from being incorrectly converted to NaN values.
Also updated the ForDemoteVectors test to check that the F32->F16, F64->F16, and F64->F32 DemoteTo ops correctly convert out-of-range finite values to positive infinity or negative infinity.

Made fix to F32 to F16 DemoteTo in generic_ops-inl.h

---

hwy/targets.h

test pass on clang 17.0.6 and gcc13.2

Enable atomic on riscv

---

hwy/contrib/math/math-inl.h

Fixed compilation error with CallSinCos on Arm by replacing `VecArg<V>&` with `V&` since `VecArg<V>&` is a typedef for `const V&` on some platforms.

Fixed CallSinCos compilation error on Arm

---

hwy/contrib/math/math-inl.h
hwy/contrib/math/math_test.cc

Added Hypot op to math-inl.h.
`Hypot(d, a, b)` returns the same result as `std::hypot(a[i], b[i])` if `a[i]` and `b[i]` are both non-NaN values, and `Hypot(d, a, b)` returns NaN if either `a[i]` or `b[i]` is NaN.
`Hypot(d, a, b)` is equivalent to `Sqrt(MulAdd(a, a, Mul(b, b)))`, but `Hypot(d, a, b)` will scale both `a[i]` and `b[i]` down prior to the multiplications if necessary to ensure that the multiplication ops result in finite values if `a[i]` and `b[i]` are both finite values.

Added Hypot op

---

g3doc/quick_reference.md

This pull request fixes the documentation for the type signature of SignBit and removes the extra `T` argument.

Fix the documentation for the type signature of SignBit

---

hwy/ops/x86_128-inl.h

Updated SSE2/SSSE3 Trunc/Ceil/Floor ops to do the float to int conversion using ConvertInRangeTo instead of ConvertTo since the SSE2/SSSE3 Trunc/Ceil/Floor ops have an IfThenElse that will simply return `v[i]` if `v[i]` is outside of the range of `MakeSigned<T>`.

Updated SSE2/SSSE3 Trunc/Ceil/Floor to use ConvertInRangeTo

---

hwy/detect_compiler_arch.h
hwy/targets.cc

Fixes issue #2125
Updated hwy/targets.cc to check that tail agnostic mode, mask agnostic mode, and that the length of a vuint8m1_t vector is at least 16 bytes on RVV.

Fix RVV target detection

---

hwy/contrib/thread_pool/topology.cc

Added workaround for the -Wsign-conversion warning that is triggered by `CPU_ISSET(static_cast<int>(lp), &set)` and `CPU_SET(static_cast<int>(lp), &set)` when topology.cc is compiled with GCC by suppressing the -Wsign-conversion warnings that GCC emits with `CPU_ISSET(static_cast<int>(lp), &set)` and `CPU_SET(static_cast<int>(lp), &set)` on Linux and FreeBSD.
The documentation of the CPU_ISSET and CPU_SET macros expect the first argument to CPU_ISSET and CPU_SET to be an int (according to https://www.gnu.org/software/libc/manual/html_node/CPU-Affinity.html), but casting `lp` to an int causes a -Wsign-conversion compiler warning when compiled with GCC.

Workaround for GCC warnings with CPU_SET/CPU_ISSET in topology.cc

---

hwy/contrib/thread_pool/topology.cc

Added casts to size_t, uint16_t, or int in hwy/contrib/thread_pool/topology.cc to fix compiler warnings

Fix Clang compiler warnings in topology.cc

---

hwy/targets.cc

Added `.option arch, +v` to inline assembly in RVV DetectTargets to fix compilation errors with Clang on RISC-V if the `-march=rv64gcv1p0` or `-march=rv32gcv1p0` option is not specified.

Fix for RVV DetectTargets inline asm with Clang

---

hwy/targets.cc

Made changes to inline assembly in targets.cc to enable ".option arch, +v" on RISC-V when compiled with GCC 13 or later to avoid errors by RISC-V GNU assembler if compiled without -march=rv64gcv1p0 or -march=rv32gcv1p0.

Fix for compilation error in targets.cc on RISC-V with GCC if compiled without -march=rv64gcv1p0

---

hwy/highway.h

Fixed compilation errors if HWY_DISPATCH_MAP is 1 by moving the declaration of hwy::AllExports to before the declaration of hwy::FunctionCache as `hwy::FunctionCache<RetType, Args...>::ChooseAndCall<kHash>(Args...)` requires that hwy::AllExports be declared if HWY_DISPATCH_MAP is 1.

Fix compilation errors if HWY_DISPATCH_MAP is 1

---

hwy/targets_test.cc

Fixes for undefined behavior that can occur in FakeFunctionDispatcher and CallFunctionForTarget in hwy/targets_test.cc if the HWY_SCALAR target is enabled.

Made UB fixes in targets_test if HWY_SCALAR is enabled

---

hwy/highway.h

Reimplemented HWY_EXPORT_T for C++11/C++14 to remove dependency on std::map.
The following lines of code in the updated HWY_EXPORT_T macro for C++11/C++14 declares a const object of an unnamed struct that has a different type from any other object:
```
static const struct {                                                       \
} HWY_CONCAT(TABLE_NAME, HighwayDispatchExportsKey) = {};                   \
```
`decltype(HWY_CONCAT(TABLE_NAME, HighwayDispatchExportsKey))` then can then be used as a template argument to FunctionCache::ChooseAndCall as `decltype(HWY_CONCAT(TABLE_NAME, HighwayDispatchExportsKey))` is unique for each table that is declared by `HWY_EXPORT_T`.
The reimplementation of C++11/C++14 HWY_EXPORT_T in this pull request fixes compilation errors that are there with GCC 8 …

Made fixes to C++11/C++14 HWY_EXPORT_T

---

CMakeLists.txt

Updated CMakeLists.txt to compile Google Highway in C++17 mode by default if CMAKE_CXX_STANDARD is not set and the C++ compiler supports C++17 mode.
With the changes made to CMakeLists.txt in this pull request, Google Highway will still be compiled in C++11 mode if CMAKE_CXX_STANDARD is set to 11 and Google Highway will still be compiled in C++14 mode if CMAKE_CXX_STANDARD is set to 14.

Updated CMakeLists.txt to compile Highway in C++17 mode by default

---

hwy/tests/interleaved_test.cc

Fixed compilation errors with interleaved_test.cc on x86 if AVX3 targets are enabled.

Fixed compilation errors with interleaved_test.cc on x86

---

hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h

Resolves issue #2183
Updated PromoteInRangeTo/DemoteInRangeTo/ConvertInRangeTo/NearestIntInRange ops that are wrappers around SSE2/AVX2/AVX3 float to integer intrinsics on x86 to use inline assembly when compiling with GCC to work around possible undefined behavior if `v[i]` is outside of the range of `TFromD<D>` (after truncation or rounding to nearest).
Similar inline assembly workarounds were implemented for float to integer conversions on PPC8/PPC9/PPC10/NEON in pull request #1919.
Note that `{%1, %0|%0, %1}` is used instead of `%1, %0` in the inline assembly statements as we want the operands to the SSE2/AVX2/AVX3 floating point to integer instructions in the inline assembly code to appear in the correct order in Compiler Explorer if Intel asm syntax is enabled.
`%v` is also used in …

Workaround for UB in x86 ConvertInRangeTo with GCC

---

hwy/ops/rvv-inl.h

This pull request adds an optimized implementation of the `Lt128` operator for RVV targets. The new implementation is synthesized using a program synthesizer.
The main computations use LMUL 1/8, which is usually more efficient than vector groups (LMUL > 1) and can outperform full vector registers (LMUL = 1) on some microarchitectures.

Optimized `Lt128` operator for RVV

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/scalar-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/float_test.cc

Added F64 to I32 DemoteToNearestInt op as SSE2/SSSE3/SSE4/AVX2/AVX3/RVV have instructions for round-to-nearest F64 to I32 conversions.
Also added NearestInt op for F64 vectors if HWY_HAVE_FLOAT64 is 1 as AVX3/AArch64 NEON have instructions for round-to-nearest F64 to I64 conversions and as x86_64 can do a scalar round-to-nearest conversion from F64 to I64 using the cvtsd2si instruction.
Also added NearestInt op for F16 vectors if HWY_HAVE_FLOAT16 is 1 as NEON_BF16/AVX3_SPR have instructions for round-to-nearest F16 to I16 conversions.
There are also use cases for F64 to I32 DemoteToNearestInt in the implementation of Exp2 in hwy/contrib/math/math-inl.h.

Added DemoteToNearestInt and F16/F64 NearestInt ops

---

.github/workflows/build_test.yml

Added Clang 16/17/18 and GCC 13 to GitHub workflow
Disabled AVX3_SPR and AVX3_ZEN4 targets with Clang 16/17/18 in GitHub workflow builds due to crashes that occur when several of the Google Highway tests are compiled on x86_64 with Clang 16 or later with all x86 Highway targets enabled. Need to break up the Google Highway tests that crash when compiled with Clang 16 or later with all x86 Highway targets enabled.

Added Clang 16/17/18 and GCC 13 to GitHub workflow

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/emu128-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/rvv-inl.h
hwy/ops/scalar-inl.h
hwy/ops/wasm_128-inl.h
hwy/ops/wasm_256-inl.h
hwy/ops/x86_128-inl.h
hwy/tests/arithmetic_test.cc

Added I8/I16/I32/U32/I64/U64 AverageRound ops as RVV/SVE2/Z14 have AverageRound instructions for all integer vector types (including both signed integer vectors and unsigned integer vectors) and as NEON/PPC have AverageRound instructions for I8/I16/I32/U32 vectors.

Added I8/I16/I32/U32/I64/U64 AverageRound ops

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/rvv-inl.h
hwy/tests/shift_test.cc

Added RoundingShiftRight/RoundingShiftRightSame/RoundingShr ops as NEON/RVV/SVE2 have instructions for rounding right shifts.
This pull request resolves one of the issues raised in issue #2248.

Added RoundingShiftRight[Same]/RoundingShr ops

---

hwy/base.h

To fix #2267, where "Native" and "native" are used without being defined.
After making this change, MSVC 2019 no longer has any errors in the error list.

Fake definitions for "Native" and "native" when HWY_IDE is defined and target does not support 16-bit floating point numbers

---

g3doc/quick_reference.md
hwy/ops/arm_neon-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/x86_128-inl.h
hwy/tests/float_test.cc

Added CeilInt and FloorInt ops as AArch64 NEON has instructions for round towards negative infinity (floor) and round towards positive infinity (ceiling) floating point to integer conversions and to provide a more efficient platform-specific implementation of CeilInt/FloorInt on SSE2 and SSSE3.

Added CeilInt and FloorInt ops

---

hwy/contrib/sort/vqsort-inl.h

Added workaround for -Waggressive-loop-optimizations that is emitted by GCC by `st.Swap(lanes + 0, lanes + i)` in HeapSort/HeapSelect.

Workaround for GCC warning in HeapSort/HeapSelect

---

BUILD
CMakeLists.txt
g3doc/quick_reference.md
hwy/ops/generic_ops-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/mul_by_pow2_test.cc

Resolves issue #2266.
Should `MulByFloorPow2(a, b)` have implementation-defined behavior in the case where `a[i]` is NaN and `b[i]` is negative infinity as the AVX3 _mm_scalef_ph/ps/pd ops return zero in the case where `a[i]` is NaN and `b[i]` is negative infinity whereas the default `MulByFloorPow2(a, b)` implementation returns NaN in any lanes where `a[i]` is NaN and `b[i]` is negative infinity?

Added MulByPow2 and MulByFloorPow2 ops

---

hwy/detect_targets.h

Resolves issue #2279.
This pull request marks the PPC8/PPC9/PPC10 targets as broken on 32-bit PowerPC to fix issues with compiling Google Highway on 32-bit PowerPC.

Fix compilation errors on 32-bit PowerPC

---

hwy/contrib/sort/vqsort-inl.h

Internally this may be translated to `BlendedStore(FirstN)` but `StoreN` guarantees no memory access beyond the end of the array.
Fixes #2281

VQSort: Replace BlendedStore at edges with StoreN

---

hwy/base.h

Fixed hwy::IsInteger implementation to ensure that `hwy::IsInteger<T>()` returns true in the case where `!hwy::IsSame<T, RemoveCvRef<T>>() && hwy::IsInteger<RemoveCvRef<T>>()` is true.

Made fixes to hwy::IsInteger

---

hwy/contrib/dot/dot_test.cc
hwy/contrib/unroller/unroller_test.cc
hwy/examples/skeleton_test.cc
hwy/ops/set_macros-inl.h

Clang 19.1.0 `(++20240810103829+866686180a31-1~exp1~20240810103957.18)` is able to successfully compile all of the Highway tests with AVX3_SPR F16 support enabled with the changes made to dot_test.cc, skeleton_test.cc, and unroller_test.cc in this pull request.
AVX3_SPR F16 support is not enabled when compiling with Clang 18 or earlier as there is a bug in LLVM 18 that causes Clang 18 to crash if AVX3_SPR F16 support is enabled, and that bug is described at https://github.com/llvm/llvm-project/issues/92035.

Enable AVX3_SPR F16 support with Clang 19.1 or later

---

hwy/base.h
hwy/contrib/sort/vqsort-inl.h

Updated hwy/base.h to ensure that `<ostream>` is not included by hwy/base.h if HWY_NO_LIBCXX is defined.
Also updated vqsort-inl.h to fix a compiler warning that occurs in the Order typedef in the the Recurse function in non-debug builds.

Fixes to hwy/base.h and vqsort-inl.h

---

CMakeLists.txt

As simple as that. One line change in CMakeLists.txt
Tested on risc-v which not supported vectors but compiled it (failed on tests)

Add RVV linker flag in case of building with RVV

---

hwy/base.h
hwy/base_test.cc

Added `operator+=(T1&, hwy::float16_t)`, `operator-=(T1&, hwy::float16_t)`, `operator*=(T1&, hwy::float16_t)`, and `operator/=(T1&, hwy::float16_t)` operator overloads that are enabled if `T1` is an integer type, float, or double and `HWY_HAVE_SCALAR_F16_TYPE` is 1.
Also added `operator+=(T1&, hwy::bfloat16_t)`, `operator-=(T1&, hwy::bfloat16_t)`, `operator*=(T1&, hwy::bfloat16_t)`, and `operator/=(T1&, hwy::bfloat16_t)` operator overloads that are enabled if `T1` is an integer type, float, or double and `HWY_HAVE_SCALAR_BF16_TYPE` is 1.
The additional `+=`, `-=`, `*=`, and `/=` operator overloads in this pull request fix compilation errors that occur in functions such as the following when compiled with Clang:
```
double SomeFunction(double a, hwy::float16_t f16_val) {
double result = a; …
```

Added additional arithmetic assignment operators from F16/BF16

---

hwy/ops/ppc_vsx-inl.h

Made changes to F64->I64/U64 DemoteTo to work around a bug that occurs with Clang 19 on Z14/Z15.
Also updated detail::I128Subtract and detail::SumOfU32OrU64LanesAsU128 to work around bugs in the Clang `<vecintrin.h>` header.
All of the Google Highway tests will pass on Z14/Z15 targets with Clang 19.1 or later with the changes in this pull request.

Fixes for Clang 19 bugs on the Z14/Z15 targets

---

hwy/ops/rvv-inl.h

This pull request may improve the performance for `Dup128MaskFromMaskBits` on certain micro-architectures.
In the original implementation, the operator uses `Set` operator to load the bits into a full vector register, then reinterprets the result to a mask.
The patch only loads the bits into a sufficient partial vector, which may be faster on certain micro-architectures like SiFive X280.

Reduce LMUL for Dup128MaskFromMaskBits

---

hwy/contrib/sort/sort_test.cc

Fixed compilation error in TestAllSortIota in hwy/contrib/sort/sort_test.cc that is triggered if either compiling in C++11/C++14 mode or if VQSORT_ENABLED is 0.

Fixed compilation error in sort_test

---

CMakeLists.txt

Currently its only compilable for RV64 when RVV is enabled, this will extend it to build for RV32 with RVV as well

Add cmake check for deducing 32bit or 64bit RISCV

---

hwy/ops/rvv-inl.h

This pull request optimizes `Lt128Upper`, `Eq128Upper` and `Ne128Upper` with the similar approach as #2079 and #2343.

Optimize Lt128Upper, Eq128Upper, and Ne128Upper

---

hwy/tests/concat_test.cc

Updated TestConcatOddEven in concat_test.cc to fix compiler warning with hwy::Unpredictable1 (which returns a signed integer).

Fixed compile error in concat_test.cc

---

hwy/detect_targets.h

Fixes issue #2356.
This pull request markets the SVE targets as broken on macOS/iOS/iPadOS on AArch64 as none of the current Apple CPU's (at least up to and including the latest M4 and A18) currently support SVE or SVE2.

Mark SVE targets as broken on macOS on A64

---

hwy/ops/x86_128-inl.h

Updated implementation of U16 Min on SSE2/SSSE3 to use `_mm_sub_epi16(a.raw, _mm_subs_epu16(a.raw, b.raw))` as `_mm_sub_epi16(a.raw, _mm_subs_epu16(a.raw, b.raw))` is more efficient than `detail::MinU(a, b)` for U16 vectors on SSE2/SSSE3.
Updated implementation of U16 Max on SSE2/SSSE3 to use `_mm_add_epi16(a.raw, _mm_subs_epu16(b.raw, a.raw))` as `_mm_add_epi16(a.raw, _mm_subs_epu16(b.raw, a.raw))` is more efficient than `detail::MaxU(a, b)` for U16 vectors on SSE2/SSSE3.
Clang 14 and later will optimize U16 `detail::MinU(a, b)` down to movdqa+psubusw+psubw on SSE2/SSSE3 when optimizations are enabled, but Clang 13 and earlier, GCC 14 and earlier, and MSVC will fail to optimize U16 `detail::MinU(a, b)` down to movdqa+psubusw+psubw when optimizations are enabled.
Likewise, Clang 14 and …

Made enhancements to SSE2/SSSE3 U16 Min/Max

---

hwy/ops/arm_neon-inl.h

this small commit fixes compiling error on some arm32 devices. cuz lack of `float64x1_t` definition. ( `float64x1_t` is only available on aarch64 [document](https://arm-software.github.io/acle/neon_intrinsics/advsimd.html)).
```
[build] In file included from /workspaces/demo/builds/release/_deps/highway-src/hwy/highway.h:588:0,
[build]                  from /workspaces/demo/builds/release/_deps/highway-src/hwy/timer-inl.h:26,
[build]                  from /workspaces/demo/builds/release/_deps/highway-src/hwy/nanobenchmark.cc:28:
[build] /workspaces/demo/builds/release/_deps/highway-src/hwy/ops/arm_neon-inl.h:2494:12: error: ‘float64x1_t’ does not name a type
[build]  HWY_INLINE float64x1_t vrecpe_f64(float64x1_t raw) {
[build]             ^~~~~~~~~~~
[build] ninja: build stopped: …
```

fix compile error on arm32 (missing float64x1_t type)

---

hwy/contrib/sort/bench_sort.cc

Added HWY_TEST_MAIN() to hwy/contrib/sort/bench_sort.cc to fix linker error if HWY_TEST_STANDALONE is 1.

Fixed linker error in bench_sort.cc if HWY_TEST_STANDALONE is 1

---

BUILD
CMakeLists.txt
hwy.gni
hwy/contrib/unroller/unroller_test.cc
hwy/detect_targets.h
hwy/foreach_target.h
hwy/highway.h
hwy/ops/set_macros-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h
hwy/ops/x86_avx3-inl.h
hwy/targets.cc
hwy/targets.h
hwy/targets_test.cc

Added preliminary support for the HWY_AVX10_2 (AVX10.2 with 256-bit vectors) and HWY_AVX10_2_512 (AVX10.2 with 512-bit vectors) targets.
Added CPUID detection for AVX10.1 and AVX10.2 support in hwy/targets.cc.
Also added a new hwy/ops/x86_avx3-inl.h header, and moved some of the AVX3/AVX10-specific ops that have dependencies on hwy/ops/x86_512-inl.h if HWY_MAX_BYTES == 64 into the new hwy/ops/x86_avx3-inl.h.
Also moved some of the AVX3/AVX3_DL-specific ops that operate on 256-bit or smaller vectors into hwy/ops/x86_128-inl.h and hwy/ops/x86_256-inl.h to support AVX10.2 targets that do not support 512-bit vectors.
Also refactored some of the AVX3 target macros in hwy/ops/set_macros-inl.h as follows:
- Added a new HWY_TARGET_STR_AVX3_VL512 macro that expands to ",evex512" for GCC/Clang …

Added AVX10_2 and AVX10_2_512 targets

---

CMakeLists.txt

Made a fix to CMakeLists.txt to correctly detect RISCV_XLEN if cross-compiling for RISC-V target with Clang.

Fix for RISC-V CMake detection if cross-compiling for RISC-V target with Clang

---

hwy/ops/set_macros-inl.h

Updated hwy/ops/set_macros-inl.h to enable tuples for the HWY_RVV target with Clang 17 or later.

Enable tuples on RVV with Clang 17 or later

---

hwy/detect_targets.h
hwy/ops/ppc_vsx-inl.h

Resolves issue #2409.
Made fixes to F32->F64 PromoteTo and F64->F32 DemoteTo to work around compiler errors on Z14/Z15 with GCC 8 or GCC 9.
Also made fixes to Reverse on Z14 with GCC 8 to work around the missing vec_reve intrinsic on Z14 with GCC 8 or earlier.
Also marked Z15 target as broken with GCC 8 or earlier as the Z15 target requires GCC 9 or later.
Also marked Z14 and Z15 targets as broken with Clang 18 or earlier due to LLVM bugs in LLVM 18 or earlier on Z14/Z15 that were fixed in LLVM 19, including a bug in LLVM 18 and earlier that was fixed in commit https://github.com/llvm/llvm-project/commit/7e4c6e98fa05f5c3bf14f96365ae74a8d12c6257 (which made its way into LLVM 19 and later).

Fixes for ZSeries with GCC 9 or earlier or Clang 18 or earlier

---

hwy/contrib/unroller/unroller-inl.h
hwy/contrib/unroller/unroller_test.cc

Currently unroller does not allow const inputs, which seems like a bug to me. The options are either `const_cast` or copying to writeable memory...
The proposed change is technically a breaking one, but only for clients who override unroller `*Load*` methods. Fix is just adding `const`...
Ping me internally if this breaks anything at Google, I'll help.

Unroller: allow const input

---

hwy/ops/rvv-inl.h

This pull request
1. implements the `Get` and `Set` operators for RVV, which correspond to the `__riscv_vget*` and `__riscv_vset*` intrinsics, respectively.
2. optimizes the `Concat*` operators with `Get` and `Set`.
There are new type categories introduced (`_GET_SET`, `_GET_SET_VIRT`, `_GET_SET_SMALLEST`). The reason why new categories are introduces is:
1. RVV only provide `vget` and `vset` intrinsics for non-fractional vector types as the whole register movement instructions are only available for LMUL >= 1. This corresponds to the `_GET_SET` category. We cannot simply reuse the `_TRUNC` category as it contains fractional vector types.
2. The `_GET_SET_VIRT` category simulates the intrinsics using instructions other than whole register movement. The result is a register with half in …

Add Get/Set for vectors and use them to implement Concat* operators for RVV

---

hwy/detect_targets.h

GCC-13 seems to be ok:
* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=i386&ver=1.1.0-3&stamp=1717006825&raw=0

Allow compilation of AVX2 on x86

---

hwy/contrib/sort/shared-inl.h

This allows us to check whether our compiler is compatible with VQSort during build of our dynamic dispatch sources

Add VQSORT_COMPILER_COMPATIBLE, split from VQSORT_ENABLED

---

hwy/ops/rvv-inl.h

Made fixes to `detail::Set<kIndex>(d, dest, v)` in hwy/ops/rvv-inl.h to ensure that any lanes past the first `Lanes(d) / 2` lanes of `dest` are not overwritten if `!detail::IsFull(d)` is true.
The fixes to `detail::Set<kIndex>(d, dest, v)` in this pull request fix bugs in the RVV Combine, ConcatLowerLower, ConcatLowerUpper, ConcatUpperLower, and ConcatUpperUpper ops if `!detail::IsFull(d)` is true.

Fixes to RVV Concat/Combine ops

---

hwy/nanobenchmark.cc

We have a use case where the highway library is linked into a shared object. Currently whenever it is dlopen'ed, the static initializer runs including running the `platform::TimerResolution`. This has been observed in profiling and raised some questions, namely it shouldn't be necessary to initialize the benchmarking code if we are using the highway library but not to benchmark anything.
Furthermore, doing so is against many companies' C++ guidelines, making this a blocker for inclusion into companies' code bases.
This commit changes this variable from a namespace-scope static variable into a static local variable.

Defer the call to get timer resolution until needed

---

hwy/base.h

Replaced `__has_builtin(__builtin_unreachable)` with `HWY_HAS_BUILTIN(__builtin_unreachable)` in hwy/base.h to fix a compiler error with GCC 9 or earlier as `__has_builtin` is not available with GCC 9 or earlier.

Fix for compiler error with GCC 9 or earlier

---

hwy/ops/ppc_vsx-inl.h

Resolves issue #2443.
This pull request adds detail::VsxXvcvspsxds and detail::VsxXvcvspuxds, which are wrappers around the VSX xvcvspsxds and xvcvspuxds instructions.
__builtin_vsx_xvcvspsxds is replaced with detail::VsxXvcvspsxds in the implementations of F32->I64 PromoteTo, F32->I64 PromoteUpperTo, F32->I64 PromoteOddTo, and F32->I64 PromoteUpperTo on PPC8/PPC9/PPC10.
__builtin_vsx_xvcvspuxds is replaced with detail::VsxXvcvspuxds in the implementations of F32->U64 PromoteTo, F32->U64 PromoteUpperTo, F32->U64 PromoteOddTo, and F32->U64 PromoteUpperTo on PPC8/PPC9/PPC10.
detail::VsxXvcvspsxds takes a `Vec128<float, N>` vector and returns the result of the VsxXvcvspsxds instruction as a `Vec128<int64_t, ((N + 1) / 2)>` vector.
detail::VsxXvcvspuxds takes a `Vec128<float, N>` vector and …

Fix for GCC 15 compiler error on PPC8/PPC9/PPC10

---

hwy/base.h
hwy/base_test.cc
hwy/ops/emu128-inl.h

Added `hwy::PositiveInfOrHighestValue<T>()`, which returns positive infinity if `T` is a floating point type or `hwy::HighestValue<T>()` if `T` is an integer type.
Also added `hwy::NegativeInfOrLowestValue<T>()` which returns negative infinity if `T` is a floating point type or `hwy::HighestValue<T>()` if `T` is an integer type.
Also updated EMU128 ReduceMin/ReduceMax to use `hwy::PositiveInfOrHighestValue<T>()` and `hwy::NegativeInfOrLowestValue<T>()`.

Added PositiveInfOrHighestValue and NegativeInfOrLowestValue

---

g3doc/quick_reference.md
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/ppc_vsx-inl.h
hwy/ops/x86_512-inl.h
hwy/tests/float_test.cc
hwy/tests/fma_test.cc

Introduces:
- Masked arithmetic operations (SqrtLower, MaskedSqrtOrZero, MaskedApproximateReciprocalSqrtOrZero, MaskedApproximateReciprocalOrZero)
- GetExponent which returns the exponents of a vector of floating point numbers. 
- MulSubAdd, a variant of MulAddSub which applied a fused multiply-add operation on even lanes and a fused multiply-subtract operation on odd ones.
Operations have been written for `arm_sve-inl.h` and `generic_ops-inl.h` and all operations have tests written for them.

Float operations SqrtLower, MulSubAdd, GetExponent etc.

---

g3doc/quick_reference.md
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/tests/masked_arithmetic_test.cc
hwy/tests/mul_test.cc

Adding special multiply operations for `arm_sve-inl.h` and `generic_ops-inl.h`: 
- MulRound multiplies two vectors of floats and returns the answer rounded to the nearest integer
- MulLower multiplies the first lane of both input vectors and passes the lanes of vector a for all other lanes.
- MulAddLower performs a multiply-accumulate operation on the first lane of the input vectors and passes the lanes of vector a for all other lanes.
Tests have been added for the operations.

MulRound, MulLower and MulAddLower ops

---

g3doc/quick_reference.md
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/tests/compare_test.cc

Introduces:
- MaskedIsNaN(v): returns mask indicating whether `v[i]` is "not a number" (unordered) or `false` if `m[i]` is false.
- MaskedIsInf(v): returns mask indicating whether `v[i]` is positive or negative infinity or `false` if `m[i]` is false.
- MaskedIsFinite(v): returns mask indicating whether `v[i]` is neither NaN nor infinity, i.e. normal, subnormal or zero or `false` if `m[i]` is false. Equivalent to `Not(Or(IsNaN(v), IsInf(v)))`.
- MaskedCompEq(m, a, b), MaskedCompNe(m, a, b), MaskedCompLt(m, a, b), MaskedCompGt(m, a, b), MaskedCompLe(m, a, b), MaskedCompGe(m, a, b), returning the output for all versions of `==, !=, <, >, >=, <=`, or `false` if `m[i]` is false.
All operations are written for both `arm_sve-inl.h` and `generic_ops-inl.h` and, equally, tests are included for all …

Masked compare and floating point classifications

---

hwy/ops/arm_sve-inl.h

SVE can load a uint8_t pointer directly into a mask through casting.
This technique is used by Arm and is known to work for GCC and Clang.
See https://gitlab.arm.com/networking/ral/-/blob/7ea3a5f7a03e7a3dd1fecd898db9802d4cd36e89/src/intrinsics.h#L422

Optimise LoadMaskBits for uint8_t on SVE

---

g3doc/quick_reference.md
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/rvv-inl.h
hwy/tests/logical_test.cc
hwy/tests/reduction_test.cc
hwy/tests/table_test.cc

Introduces:
- MaskedOrOrZero(m, a, b): returns `a[i] || b[i]` or `zero` if `m[i]` is false.
- TwoTablesLookupLanesOr(d, m, a, b, unspecified): returns the result of `TwoTablesLookupLanes(V a, V b, unspecified)` where `m[i]` is true, and `a[i]` where `m[i]` is false.
- TwoTablesLookupLanesOrZero(d, m, a, b, unspecified): returns the result of `TwoTablesLookupLanes(V a, V b, unspecified)` where `m[i]` is true, and zero where `m[i]` is false.
- MaskedReduceSum(d, m, v): returns the sum of all lanes where `m[i]` is `true`.
- MaskedReduceMin(d, m, v): returns the minimum of all lanes where `m[i]` is `true`.
- MaskedReduceMax(d, m, v): returns the maximum of all lanes where `m[i]` is `true`.
- IfNegativeThenNegOrUndefIfZero(mask, v): returns `mask[i] < 0 ? (-v[i]) : ((mask[i] > 0) ? v[i] : …

Various masked operations

---

g3doc/quick_reference.md
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/tests/fma_test.cc
hwy/tests/masked_arithmetic_test.cc
hwy/tests/masked_minmax_test.cc

Introduces:
- MaskedMaxOrZero(m, a, b): returns `Max(a, b)[i]` or `zero` if `m[i]` is false
- MaskedAddOrZero(m, a, b): returns `a[i] + b[i]` or `0` if `m[i]` is false.
- MaskedSubOrZero(m, a, b): returns `a[i] - b[i]` or `0` if `m[i]` is false.
- MaskedMulOrZero( m,  a, b): returns `a[i] * b[i]` or `0` if `m[i]` is false.
- MaskedDivideOrZero(m, a, b): returns `a[i] / b[i]` or `0` if `m[i]` is false.
- MaskedSaturatedAddOrZero(m, a, b): returns `a[i] + b[i]` saturated to the minimum/maximum representable value, or `0` if m[i]` is false.
- MaskedSaturatedSubOrZero(m,  a,  b): returns `a[i] - b[i]` saturated to the minimum/maximum representable value, or `0` if m[i]` is false.
- MaskedMulFixedPoint15OrZero(m, a): returns returns the result of multiplying two Q1.15 fixed-point numbers, or …

Zero masked arithmetic operations

---

BUILD
CMakeLists.txt
g3doc/quick_reference.md
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/tests/complex_arithmetic_test.cc

Introduces basic complex arithmetic for float and integer types. Some masked operations for complex numbers are also included.
A single complex value is formed of a real part which is stored in an even lane, and the imaginary part which is stored in the following odd lane.
All complex operations are written for `arm_sve-inl.h` and `generic_ops-inl.h` and a new set of tests is introduced for all the new complex operations.

Complex number operations

---

hwy/contrib/thread_pool/spin.h
hwy/contrib/thread_pool/spin_test.cc

Currently getting the following errors on a native machine with gcc-12 after [this PR](https://github.com/google/highway/pull/2471/files): 
```
spin.h:162:1: error: control reaches end of non-void function [-Werror=return-type]
162 | }
error: ‘my_reps’ may be used uninitialized [-Werror=maybe-uninitialized]
spin_test.cc:76:14: note: ‘my_reps’ was declared here
spin_test.cc:76:14: note: ‘my_reps’ was declared here
```

Fix compilation on ppc64le and s390x with gcc-12

---

CMakeLists.txt
hwy/contrib/thread_pool/futex.h
libhwy-contrib.pc.in

The changes to CMakeLists.txt in this pull request fixes build errors with GCC/Clang on Win32 if `HWY_DISABLE_FUTEX` is not defined.
Checks to detect the presence of libsynchronization.a or synchronization.lib, WaitOnAddress, WakeByAddressAll, and WakeByAddressSingle on Win32 are also added to CMakeLists.txt in this pull request.

Made fixes to Win32 build with GCC/Clang

---

hwy/contrib/thread_pool/spin.h

Currently failing on gcc-12 with:
```
error: control reaches end of non-void function [-Werror=return-type]
```

Fix build with gcc

---

hwy/base.h

clang with `-Wpedantic` issues a `-Wc++23-attribute-extensions` warning in the strict C++ <=20 mode.

Fix C++23-only attribute warning for HWY_ASSUME

---

hwy/contrib/thread_pool/thread_pool.h

Fixes compiler warning with Clang in ThreadPool::SendConfig as the task parameter in the closure lambda is unused in debug builds.

Fixes for compiler warnings in thread_pool.h

---

.github/workflows/multiarch.yml

Updated AArch64 build in .github/workflows/multiarch.yml to use a GitHub ARM64 runner (which runs on an actual AArch64 CPU) instead of using the uraimo/run-on-arch-action (which runs the AArch64 build in a Docker container on an x86_64 CPU where AArch64 executables are run using the QEMU emulator) as using an GitHub ARM64 runner is much faster than running the AArch64 build in a Docker container on an x86_64 host.

Updated AArch64 workflow to use GitHub ARM64 runner

---

hwy/ops/arm_sve-inl.h

Updated SVE I8/U8 LoadMaskBits to cast `bits` to `UnalignedSveMaskT` (which is a typedef of `svbool_t` with the `__aligned__(1)` and `__may_alias__` attributes) using `reinterpret_cast` to work around GCC/Clang compiler warnings.
`*reinterpret_cast<const UnalignedSveMaskT*>(bits)` also assumes that either `Lanes(ScalableTag<uint8_t>()) <= 64` or `Lanes(d) == Lanes(ScalableTag<uint8_t>())` is true, and it is possible for `Lanes(ScalableTag<uint8_t>()) > 64` to be true on the HWY_SVE/HWY_SVE2 targets.
Should an opt-out or opt-in be added for the optimized `*reinterpret_cast<const UnalignedSveMaskT*>(bits)` code path to avoid a crash or undefined behavior in the case where `Lanes(ScalableTag<uint8_t>()) > 64 && Lanes(ScalableTag<uint8_t>()) < Lanes(d)` as `LoadMaskBits(d)` does not expect …

Added workaround for compiler warning in SVE I8/U8 LoadMaskBits

---

g3doc/quick_reference.md
hwy/base.h
hwy/ops/arm_sve-inl.h
hwy/ops/generic_ops-inl.h
hwy/ops/shared-inl.h
hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/tests/arithmetic_test.cc

Adding special arithmetic operations for `arm_sve-inl.h` and `generic_ops-inl.h`:
* AddLower adds the first lane of both input vectors and passes the lanes of vector a for all other lanes.
* PairwiseAdd adds consecutive pairs of elements in each of the vectors and interleaves the resulting lanes.
* PairwiseSub subtracts consecutive pairs of elements in each of the vectors and interleaves the resulting lanes.
* PairwiseAdd128 adds consecutive pairs of elements in each of the vectors and then packs the results in 128 bit blocks, such that the results of vector a are in the lower half of the block and the results of vector b are in the upper half of the block.
* PairwiseSub128 subtracts consecutive pairs of elements in each of the vectors and then packs the results in 128 bit blocks, such …

AddLower, PairwiseAdd/Sub and MaskedAbsOr operations

---

hwy/contrib/thread_pool/topology.cc

This was discussed in [google/gemma.cpp#508](https://github.com/google/gemma.cpp/issues/508).

Fix the index of the cluster in LP on macOS

---

CMakeLists.txt

Updated CMakeLists.txt to only build hwy/auto_tune_test.cc if HWY_ENABLE_CONTRIB is ON as hwy/auto_tune.h and hwy/auto_tune_test.cc have dependencies on VQSort.

Fixed CMake build if HWY_ENABLE_CONTRIB is OFF

---

.github/workflows/multiarch.yml
CMakeLists.txt
hwy/detect_targets.h
hwy/highway.h
hwy/ops/generic_ops-inl.h
hwy/ops/loongarch_lasx-inl.h
hwy/ops/loongarch_lsx-inl.h
hwy/ops/set_macros-inl.h
hwy/targets.cc

Added CI tests and implemented LSX (128-bit vector extensions) and LASX (256-bit vector extensions) optimizations. welcome to review. @jan-wassenberg @jeromejj

Add loongarch support and LSX/LASX impl

---

CMakeLists.txt

As the profiler example depends on contrib (see issue #2570, commit db1facc), it should only be built if the contrib target is enabled (i.e. if `HWY_ENABLE_CONTRIB` is set to `ON`). Otherwise, Make will fail with a linker error when `HWY_ENABLE_EXAMPLES=ON` and `HWY_ENABLE_CONTRIB=OFF`.

Build profiler_example only if HWY_ENABLE_CONTRIB is ON

---

hwy/highway.h

Fixes issue #2568.
HWY_DYNAMIC_DISPATCH is updated to use hwy::PreventElision if compiling with GCC or Clang (including clang-cl), but not if compiling with MSVC.

Fix compilation error with HWY_DYNAMIC_DISPATCH with MSVC

---

hwy/aligned_allocator.cc
hwy/base.h
hwy/detect_targets.h
hwy/ops/rvv-inl.h

Fixes issue #2554 by checking that both `__riscv_v` and `__riscv_v_intrinsic` are defined as Clang 20 and later define `__riscv_v_intrinsic`, even when the RISC-V "V" extension is not enabled.
Also undid the changes made in pull request #2561 as the changes made in pull request #2561 still trigger compiler errors with Clang 20 or later on RISC-V if the RISC-V "V" extension is not enabled and Google Highway is not built with "-DHWY_COMPILE_ONLY_EMU128" or "-DHWY_COMPILE_ONLY_SCALAR".
Also updated rvv-inl.h to assume that the VXRM argument should be avoided with Clang 16 or earlier as the latest Clang 16 release from https://github.com/llvm/llvm-project (16.0.6) without any additional patches expects that the VXRM argument be avoided.

Fixes for RVV detection and re-enable RVV with Clang 16 or later or GCC 13 or later

---

hwy/ops/rvv-inl.h
hwy/ops/set_macros-inl.h

The changes made in this pull request and pull request #2586 allow dynamic dispatch to be enabled on RISC-V with Clang 20 or later without the `-march=rv64gcv1p0` option if the `-DHWY_HAVE_RUNTIME_DISPATCH_LINUX=1` is specified.
The changes in this pull request fixes issues raised in issue #2554.
Should runtime dispatch be enabled by default on Linux on RISC-V when compiling with Clang 20 or later once the changes in this pull request and pull request #2586 are merged?

Fixes to compilation errors with RVV with EMU128 or SCALAR baseline

---

hwy/ops/x86_512-inl.h

Updated GetExponent in hwy/ops/x86_512-inl.h to suppress GCC compiler warnings.

Fixed compiler warnings in GetExponent on AVX3 with GCC

---

hwy/ops/x86_128-inl.h
hwy/ops/x86_256-inl.h
hwy/ops/x86_512-inl.h

Updated F32->UI32 ConvertTo, F64->UI64 ConvertTo, F32->UI64 PromoteTo, and F64->UI32 DemoteTo to use the new `_mm*_cvtts_*` intrinsics in AVX10.2 if available (requires GCC 15.1 or later or Clang 20.1.3 or later).
Also need to apply the fix to TestDemoteTo in pull request #2590 to avoid test failures in TestDemoteTo on the AVX10_2 target with the changes in this pull request.

Made enhancements to float to int conversions on AVX10.2

---

hwy/ops/arm_sve-inl.h

Updated SVE detail::MaskedMin/detail::MaskedMax ops for floating-point vectors to use svminnm/svmaxnm instead of svmin/svmax for behavioral consistency with Min/Max.
Also fixed the implementation of floating-point Min op for Clang in arm_sve-inl.h to return `a` if `b` is NaN to ensure consistency with the SVE svminnm op.
The fixes in this pull request fix test failures with SVE when compiling with Clang.

Made fixes to SVE Min, MaskedMin, and MaskedMax

---

hwy/ops/arm_neon-inl.h

Updated NEON I8/I16/I32/I64 `operator+` and `operator-` ops to use unsigned addition or subtraction (a similar workaround was implemented for PPC targets in pull request #1733).
Also updated NEON I8/I16/I32 `operator*` to use unsigned multiplication.
The changes in this pull request avoid test failures if compiling with `-ftrapv` to match the behavior of x86 `_mm_add_epi*`, `_mm_sub_epi*`, and `_mm_mul_epi*` intrinsics.

Fix to I8/I16/I32/I64 Add/Sub/Mul on NEON if compiling with -ftrapv

---

hwy/ops/rvv-inl.h

This pull request improves the performance of `MulEven` by using masked multiplication instead of merging the results after computing the higher and lower parts.
A similar optimization can be applied to the `MulOdd` operator, though this would require a `MaskedMulHighOr` operator, which is currently unavailable.
For 8-bit elements, `MulEven` currently uses the immediate value 0x5555, which requires two instructions to construct on RISC-V. There may be a potential optimization by constructing the mask manually instead of relying on `Dup128MaskFromMaskBits`, allowing the use of the smaller immediate 0x55. However, it's just a scalar instruction, so I am unsure if we want to do so.

Improve MulEven performance for RVV

---

hwy/contrib/thread_pool/futex.h

Fix for compile error in thread_pool/futex.h on Win32 if HWY_DISABLE_FUTEX is defined

---

hwy/contrib/thread_pool/thread_pool.h

Config must have exact size, but bool is not guaranteed to be 1 byte. Use uint8_t instead, which is always 1 byte. Fixes the build on powerpc-darwin.
Fixes: https://github.com/google/highway/issues/2679

thread_pool.h: avoid ambiguous size types in Config struct

---

hwy/cache_control.h

`clang-cl` requires `MMX` for  `_mm_prefetch`. With `-mno-mmx`, `__MMX__` is undefined and the build fails in cache_control.h. Use `__builtin_prefetch` in this configuration; keep `_mm_prefetch` everywhere else. Fixes NumPy's CI failure on Windows without MMX.
For further details, see https://github.com/google/highway/pull/2737#issuecomment-3353074182

BLD: fallback to `__builtin_prefetch` on `clang-cl` with `-mno-mmx`
