google/highway

- hwy/tests/test_util-inl.h
fix msvc check for PreventElision (MR 123)
FUTURE_COPYBARA_INTEGRATE_REVIEW=https://github.com/google/highway/pull/123 from deymo:msvc 89b852857c84d3fb12274628ffc26d384c8fe42e
> fix msvc check for PreventElision (MR 123)

- hwy/nanobenchmark.cc
> Cast __ppc_get_timebase_freq to double

- BUILD
- CMakeLists.txt
- hwy/aligned_allocator.h
- hwy/base.h
- hwy/contrib/image/image.h
- hwy/highway_export.h
- hwy/hwy.version
- hwy/nanobenchmark.h
- hwy/targets.h
- hwy/tests/test_util.h
- libhwy.pc.in
> Implement compilation of highway as shared libraries

- CMakeLists.txt.in
> Use fixed version of gtest

- hwy/contrib/sort/vqsort-inl.h
The previous build-heap algorithm is O(N*logN).
Reference: *Introduction to Algorithms*, third edition, chap 6.3
> use O(N) build-heap in vqsort

- CMakeLists.txt
> Make sure to depends on hwy.version file for proper cmake dependencies

- hwy/ops/generic_ops-inl.h
- hwy/ops/x86_512-inl.h
- hwy/tests/mul_test.cc
I'm experiencing compilation and test failures at the moment.
I have some experience with C++20, where I can use `requires`, `concepts`, and `if constexpr` for generic programming, but I'm unfamiliar with C++11 or SFINAE.
Odds are the approach is rather poor, and focused on x86. Suggestions would be appreciated.
Fixes https://github.com/google/highway/issues/907.
> Implement i64mul

- hwy/ops/arm_neon-inl.h
- hwy/ops/arm_sve-inl.h
- hwy/ops/rvv-inl.h
- hwy/ops/wasm_128-inl.h
- hwy/ops/wasm_256-inl.h
- hwy/ops/x86_128-inl.h
- hwy/ops/x86_256-inl.h
- hwy/ops/x86_512-inl.h
- hwy/tests/convert_test.cc
Implementing unsigned integer to floating-point conversions. This fixes #917 .
> Unsigned integer to floating-point conversion

- hwy/base.h
Add a portable `HWY_ASSUME` macro for MSVC, GCC, ICC, and clang-like compilers.
Closes https://github.com/google/highway/issues/1098
> Add HWY_ASSUME macro

- README.md
Closes https://github.com/google/highway/issues/1109
> Describe the "Shift Inwards" stip-mining strategy

- CMakeLists.txt
Also prepend target names with hwy:: namespace for better CMake user experience.
> Add support for find_package + Config mode

- CMakeLists.txt
Added hwy/ops/ppc_vsx-inl.h to HWY_SOURCES in CMakeLists.txt file
> Update CMakeLists.txt to include hwy/ops/ppc_vsx-inl.h

- hwy/ops/generic_ops-inl.h
Modified the LoadInterleaved3 implementation for 8 16-bit lanes in generic_ops-inl.h to use uint8_t arrays for the indices instead of uint16_t indices.
This change to LoadInterleaved3 addresses one of the issues that is there in issue https://github.com/google/highway/issues/1169.
> Fixed issue with LoadInterleaved3 implementation in generic_ops-inl.h on big-endian targets

- hwy/ops/ppc_vsx-inl.h
Made changes to hwy/ops/ppc_vsx-inl.h to fix issues that are there on big-endian PPC8/PPC9/PPC10 targets.
Fixes issue #1169
> Fixed issues on big-endian PPC8/PPC9/PPC10 targets

- g3doc/quick_reference.md
- hwy/ops/arm_neon-inl.h
- hwy/ops/arm_sve-inl.h
- hwy/ops/ppc_vsx-inl.h
- hwy/ops/rvv-inl.h
- hwy/ops/wasm_128-inl.h
- hwy/ops/x86_128-inl.h
- hwy/ops/x86_256-inl.h
- hwy/ops/x86_512-inl.h
- hwy/tests/compare_test.cc
> Added Le and Ge operations for integer vectors

- hwy/ops/x86_128-inl.h
Made enhancements to a few of the shuffle operations on the HWY_SSE2 target.
Also updated the 32-bit signed right shift operation in x86_128-inl.h to use the _mm_srav_epi32 intrinsic on the HWY_AVX2 target as the _mm_srav_epi32 intrinsic is supported on AVX2 according to the Intel Intrinsics guide at https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html.
> Made enhancements to a few operations in x86_128-inl.h

- CMakeLists.txt
> Clarify when to use the armv7 cmake option

- docs/conf.py
The previous pr has some small bugs, after resetting the copyright, the gh-pages should be able to work
> Fix github pages cannot generate

- g3doc/op_wishlist.md
- g3doc/quick_reference.md
- hwy/contrib/dot/dot-inl.h
- hwy/examples/benchmark.cc
- hwy/highway_test.cc
- hwy/ops/arm_neon-inl.h
- hwy/ops/arm_sve-inl.h
- hwy/ops/emu128-inl.h
- hwy/ops/ppc_vsx-inl.h
- hwy/ops/rvv-inl.h
- hwy/ops/scalar-inl.h
- hwy/ops/wasm_128-inl.h
- hwy/ops/wasm_256-inl.h
- hwy/ops/x86_128-inl.h
- hwy/ops/x86_256-inl.h
- hwy/ops/x86_512-inl.h
- hwy/tests/demote_test.cc
- hwy/tests/mul_test.cc
- hwy/tests/reduction_test.cc
Feel free to suggest a better name for this new op :)
> Add SumOfLanesVal operation - reduction without broadcast

- hwy/ops/x86_128-inl.h
- hwy/ops/x86_256-inl.h
- hwy/ops/x86_512-inl.h
Re-implemented InsertLane on SSE2/SSSE3/SSE4/AVX2/AVX3 to do a Set operation followed by an IfThenElse operation.
> Made enhancements to x86 InsertLane operation

- hwy/ops/arm_sve-inl.h
- hwy/ops/rvv-inl.h
Updated RVV LoadDup128 implementation to load no more than 16 bytes from `p`.
Also updated RVV LoadDup128 implementation to avoid an unnecessary TableLookupLanes operation in the case where `d.MaxBytes() <= 16` is true.
Updated HWY_SVE2_128 implementation of LoadDup128 to simply do a Load as the size of a vector cannot exceed 16 bytes on the HWY_SVE2_128 target.
Also updated the HWY_SVE/HWY_SVE2/HWY_SVE_256 LoadDup128 implementations to simply do a Load in the case where `d.MaxBytes() <= 16` is true.
The HWY_SVE/HWY_SVE2/HWY_SVE_256 LoadDup128 implementation will still do a svld1rq operation (wrapped by the detail::LoadDupFull128 function) in the case where `d.MaxBytes() > 16` is true.
Updated the implementation of detail::LanesPerBlock in hwy/ops/rvv-inl.h and hwy/ops/arm_sve-inl.h to …
> Added fixes for LoadDup128 and detail::LanesPerBlock on RVV/SVE

- hwy/ops/x86_256-inl.h
The detail::BitsFromMask implementation for Mask256<int16_t> and Mask256<uint16_t> has been updated to use _pext_u32 instead of _pext_u64 as vectors have 32 or fewer lanes on the HWY_AVX2 target.
Also added the HWY_DISABLE_PEXT_ON_AVX2 option to disable the use of _pext_u32/_pext_u64 on the HWY_AVX2 target as Bulldozer/Zen 1/Zen 2 have AVX2 and BMI2 support but slow pext instructions.
> Updated AVX2 implementation of detail::BitsFromMask for I16/U16 masks

- hwy/highway_test.cc
- hwy/ops/rvv-inl.h
Added fix for RVV Lanes operation to deal with the fractional `N` case.
Also updated TestAllMaxLanes in hwy/highway_test.cc to verify the result of `Lanes(d)` for the cases where `N` is a fractional N.
The fix to the SVE Lanes function that is in pull request #1437 needs to be applied to get the updated version of TestAllMaxLanes (which includes the checks for the fractional N cases) to pass on the HWY_SVE and HWY_SVE2 targets.
> Implemented fix for RVV Lanes

- hwy/contrib/math/math_test.cc
> Fix compilation errors with SinCosSin and SinCosCos in math_test.cc

- hwy/ops/rvv-inl.h
Added missing HWY_INLINE to RVV detail::LanesPerBlock
> Add HWY_INLINE to RVV detail::LanesPerBlock

- hwy/contrib/unroller/unroller_test.cc
Fixes bug in FindUnit in unroller_test.cc that causes UnrollerTest to fail on AVX2
> Fix unroller_test FindUnit

- hwy/ops/ppc_vsx-inl.h
Added workaround for bug in little-endian PPC9 vec_cntlz_lsbb/vec_cnttz_lsbb intrinsic when compiled with GCC 11 or earlier.
Also updated FindFirstTrue, FindKnownFirstTrue, FindLastTrue, and FindKnownLastTrue to use vec_cntlz_lsbb/vec_cnttz_lsbb on big-endian PPC10 (as big-endian PPC10 uses the same detail::BitsFromMask implementation as PPC8/PPC9).
> Made fixes to PPC9 FindFirstTrue/FirstLastTrue

- hwy/tests/mul_test.cc
I had updated TestSatWidenMulPairwiseAdd to work around the TestAllSatWidenMulPairwiseAdd failures that were happening on the HWY_PPC9 target when compiled with GCC 12 or GCC 13 (but not GCC 11 or Clang 16), and TestAllSatWidenMulPairwiseAdd will now pass on the PPC9 target when compiled with GCC 12 with the fixes I made to TestSatWidenMulPairwiseAdd in this pull request.
> Updated TestSatWidenMulPairwiseAdd to work around PPC9 GCC 12 codegen issue

- CMakeLists.txt
> Do not install hwy_test when HWY_ENABLE_TESTS is OFF

- hwy/ops/ppc_vsx-inl.h
Added a new platform-specific PromoteUpperTo implementation for PPC as a platform-specific PromoteUpperTo implementation is more efficient than the generic PromoteUpperTo implementation for most of the half-vector to full-vector PromoteUpperTo cases on PPC.
PPC has instructions for I8->I16, I16->I32, and I32->I64 half-vector to full-vector PromoteUpperTo.
PPC9/PPC10 also have instructions for half-vector F16 to full-vector F32 PromoteUpperTo.
> Added platform-specific PromoteUpperTo implementation for PPC

- hwy/tests/reduction_test.cc
Updated TestSumOfLanes::SignedEvenLengthVectorTests to check that D has an even number of lanes using `HWY_MAX_LANES_D(D)`.
Also updated TestSumOfLanes::SignedEvenLengthVectorTests to return if `Lanes(d)` is less than 2 on targets that have scalable vectors as it is possible for `(Lanes(d) & 1) != 0 && (MaxLanes(d) & 1) == 0` to be true on targets that use scalable vectors if `Lanes(d) < 2` is true.
The changes that were made to TestSumOfLanes::SignedEvenLengthVectorTests in this pull request fixes the test failures that are encountered on the SVE target if `Lanes(ScalableTag<uint8_t>()) == 16` is true.
> Fixed bug with TestSumOfLanes on SVE

- hwy/ops/rvv-inl.h
Added missing TruncateTo for virtual LMUL on RVV to fix compilation errors on RVV target
> Added RVV TruncateTo for virtual LMUL

- hwy/ops/rvv-inl.h
Updated RVV LoadN/LoadNOr to use a tail-undisturbed load instead of a mask-undisturbed load.
A tail-undisturbed load (_tu) modifies the first `CappedLanes(num_lanes)` elements of the result vector and leaves any lanes past the first (lowest-index) `CappedLanes(num_lanes)` unchanged.
A mask-undisturbed tail-agnostic load (_mu) leaves inactive elements (those whose mask bit is not set) that are within the first (lowest-index) `CappedLanes(num_lanes)` unchanged but may possibly change any lanes past the first (lowest-index) `CappedLanes(num_lanes)` to all 1s.
Using a tail-undisturbed load instead of a mask-undisturbed load in the RVV LoadN and LoadNOr implementations fixes the errors that were encountered with TestAllLoadN and TestAllLoadNOr on the RVV target.
> Made fixes to RVV LoadN/LoadNOr

- hwy/contrib/math/math_test.cc
Fixes commit a02c342bf3b096b6c035165d3641f032e403506b
> Really disables math_test

- hwy/ops/wasm_128-inl.h
Fixes compilation errors on HWY_WASM target
> Added F16/BF16 InterleaveLower on HWY_WASM target

- CMakeLists.txt
> Add an option to opt-out of HWY_RISCV

- hwy/contrib/math/math_test.cc
> Workaround issue on ppc64el with LTO

- hwy/ops/x86_128-inl.h
- hwy/ops/x86_256-inl.h
- hwy/ops/x86_512-inl.h
Updated U8 SumsOf4 to use _mm_maskz_dbsad_epu8/_mm256_maskz_dbsad_epu8/_mm512_maskz_dbsad_epu8 on AVX3 targets.
Also added an optimized implementation of I8 SumsOf4 on AVX3 that does the following:
- Adjusts the source values of the source I8 vector to be in the 0..255 range, bitcasted to an uint8_t vector
- Sums the adjusted source values by doing an U8 SumsOf4 operation
- Adds -512 to each i32 lane of the result of the U8 SumsOf4 operation (bitcasted to an I32 vector) to account for the adjustment that was made to the source values
> Added optimized implementations of I8/U8 SumsOf4 for AVX3

- README.md
See: https://github.com/libvips/libvips/pull/3618
> Docs: add libvips to list of users

- .github/workflows/build_test.yml
See:
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110643
> Detect signed arithemtic overflow in GCC github/CI

- hwy/ops/arm_neon-inl.h
Link: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110643
Suggested-by: Andrew Pinski <pinskia@gcc.gnu.org>
> Fix UB case with signed overflow, prefer unsigned

- hwy/ops/ppc_vsx-inl.h
Made changes to PPC F32->U32, F64->I64, and F64->U64 ConvertTo routines to prevent GCC/Clang from incorrectly optimizing out the vec_ctu, vec_cts, or __builtin_convertvector operation if the values of any lanes of `v[i]` are outside of the range of the type being converted to.
Also updated the PPC F64->I64 and F64->U64 ConvertTo routines to use __builtin_convertvector on Clang to ensure that values are correctly converted as Clang F64->I64 vec_cts converts values using xvcvdpsxws instead of xvcvdpsxds if `__XL_COMPAT_ALTIVEC__` is defined and as Clang F64->I64 vec_ctu converts values using xvcvdpuxws instead of xvcvdpuxds if `__XL_COMPAT_ALTIVEC__` is defined.
Here is a link to a Compiler Explorer snippet that shows constant vectors with out-of-range values being incorrectly converted …
> Made fixes to PPC float to int ConvertTo

- hwy/base.h
- hwy/ops/emu128-inl.h
- hwy/ops/scalar-inl.h
Added the following new operations in hwy/base.h:
- RemoveCvRef&lt;T&gt; ScalarAbs(T val) - returns absolute value of floating point or integer
- bool ScalarIsNaN(T val) - returns true if `val` is NaN and false otherwise
- bool ScalarIsInf(T val) - returns true if `val` is infinity and false otherwise
- bool ScalarIsFinite(T val) - returns true if `val` is a finite value and false otherwise
- RemoveCvRef&lt;T&gt; ScalarCopySign(T magn, T sign) - returns the number with the magnitude of `magn` and sign of `sign`
- bool ScalarSignBit(T val) - returns the sign bit of `val`
All 6 of the above operations are supported for the `float`, `double`, `hwy::float16_t` and `hwy::bfloat16_t` types.
ScalarAbs and ScalarIsFinite are also supported also for integer types (including unsigned integer …
> Added new scalar float and integer ops in hwy/base.h

- .github/workflows/multiarch.yml
> Add testing on foreign archs

- hwy/ops/ppc_vsx-inl.h
Added #undef HWY_S390X_HAVE_Z15 to the ppc_vsx-inl.h header
> Added #undef HWY_S390X_HAVE_Z15 to ppc_vsx-inl.h

- hwy/ops/generic_ops-inl.h
The implementation of F32->F16 DemoteTo implementation in hwy/ops/generic_ops-inl.h in this pull request is much more efficient than the current F32->F16 DemoteTo implementation in hwy/ops/generic_ops-inl.h on some targets, including SSE2/SSSE3/SSE4.
A snippet showing the difference in codegen between the two F32->F16 DemoteTo implementations can be found at https://godbolt.org/z/snqa49Wj6.
The updated F32->F16 implementation in this pull request also uses a F32 Add operation to shift the mantissa bits down, which also rounds the mantissa to the nearest value (instead of simply truncating the mantissa).
Shifting the mantissa bits down using an F32 Add operation also avoids the overhead that is there with Shl/Shr on SSE2/SSSE3/SSE4, which lack instructions for per-lane variable shifts.
> Reimplemented F32->F16 DemoteTo in generic_ops-inl.h

- .github/workflows/build_test.yml
Updated GitHub workflow to check that Highway successfully compiles in C++11/14/17/20 mode.
> Updated GitHub workflow to check that Highway successfully compiles in C++11/14/17/20 mode

- hwy/base.h
- hwy/base_test.cc
- hwy/ops/emu128-inl.h
- hwy/ops/scalar-inl.h
Added ScalarShr operation, which guarantees that signed right shifts are arithmetic right shifts.
Also updated EMU128/SCALAR Shr, ShiftRight, ShiftRightSame, and BroadcastSignBit ops to use ScalarShr.
GCC also guarantees that `(val >> shift_amt)` is an arithmetic right shift if `val` is a signed integer according to https://gcc.gnu.org/onlinedocs/gcc-4.8.0/gcc/Integers-implementation.html.
MSVC also guarantees that `(val >> shift_amt)` is an arithmetic right shift if `val` is a signed integer according to https://learn.microsoft.com/en-us/cpp/cpp/left-shift-and-right-shift-operators-input-and-output?view=msvc-140.
> Added ScalarShr operation

- hwy/ops/rvv-inl.h
Section 6.3 of the RVV specification, which can be found at https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc, allows the __riscv_vsetvl_e* intrinsics to return a value of less than `cap` but at least `(cap + 1) / 2` if all of the following are true:
- `cap >= 5`
- `(cap & (cap - 1)) != 0` (in other words, `cap` is not 0 or a power of 2)
- `cap > Lanes(ScalableTag<TFromD<decltype(d)>, d.Pow2()>())`
- `cap < 2 * Lanes(ScalableTag<TFromD<decltype(d)>, d.Pow2()>())`
We want `CappedLanes(d, cap)` to return the same result as `HWY_MIN(d, Lanes(d))` as the as `LoadN(d, p, cap)` operation expects to load exactly `HWY_MIN(cap, Lanes(d))` lanes and as the `StoreN(v, d, p, cap)` operation expects to store exactly `HWY_MIN(cap, Lanes(d))` lanes, even on RVV implementations where vsetvl …
> Fixes to RVV CappedLanes

- hwy/abort.cc
- hwy/aligned_allocator.cc
- hwy/base.h
- hwy/contrib/sort/vqsort.cc
- hwy/detect_compiler_arch.h
- hwy/detect_targets.h
- hwy/foreach_target.h
- hwy/ops/emu128-inl.h
- hwy/targets.cc
- hwy/targets.h
- hwy/tests/convert_test.cc
- hwy/tests/test_util-inl.h
- hwy/timer-inl.h
- hwy/timer.cc
RVV isn't  arch name. We should use RISCV
> Replace HWY_ARCH_RVV with HWY_ARCH_RISCV

- README.md
This closes https://github.com/google/highway/issues/2065
> Correct ambiguous text in README

- hwy/contrib/math/math-inl.h
- hwy/contrib/math/math_test.cc
Added implementation of Exp2 to math-inl.h.
> Added Exp2 op

- hwy/contrib/bit_pack/bit_pack-inl.h
Fixed compiler errors in bit_pack-inl.h in C++11/C++14 mode by using the NextUnroller typedef in Unroller::pack and Unroller::unpack, which prevents unnecessary template instantiation in the case where C++17 if constexpr support is not available.
> Made C++11/C++14 compilation fixes to Unroller in bit_pack-inl.h

- hwy/ops/rvv-inl.h
Resolves issue #2140.
Updated Ceil and Floor on RVV to use detail::CeilInt and detail::FloorInt (which are wrappers around the RVV __riscv_vfcvt_x_f_v_i*_rm intrinsic) with GCC 14 and later and Clang 17 to fix reordering bugs with changing floating-point rounding mode using inline assembly with Clang 16 and later.
Also changed implementation of RVV Ceil and Floor with GCC 13 and earlier and Clang 16 and earlier to avoid changing the floating-point rounding mode using inline assembly, which fixes bugs with RVV Ceil/Floor with Clang 16 and later and fixes test failures on RVV with Clang 16 and later.
Also updated F64->F32 and F32->F16 DemoteTo on RVV to use the __riscv_vfncvt_f_f_w_f intrinsics instead of the __riscv_vfncvt_rod_f_f_w_f intrinsics as the __riscv_vfncvt_rod_f_f_w_f intrinsics …
> Made fixes to RVV Ceil, Floor, and F->F DemoteTo

- hwy/ops/ppc_vsx-inl.h
Updated detail::BitsFromMask on Z14/Z15 to use ExtractSignBits as Z14/Z15 has the vec_bperm_u128 intrinsic that is equivalent to PPC8/PPC9/PPC10 vec_vbpermq intrinsic.
> Updated detail::BitsFromMask on Z14/Z15

- hwy/contrib/thread_pool/futex.h
For reference:
* https://buildd.debian.org/status/fetch.php?pkg=highway&arch=hurd-i386&ver=1.1.0-1&stamp=1716577724&raw=0
> Allow compilation with -Werror on GNU/Hurd system

- hwy/ops/generic_ops-inl.h
Fixed the default BitShuffle implementation on big-endian targets in generic_ops-inl.h, which fixes bugs with BitShuffle on EMU128 on big-endian.
The behavior of BitShuffle in generic_ops-inl.h now matches the behavior of BitShuffle in ppc_vsx-inl.h on big-endian PPC/Z14 with the fixes in this pull request.
TestAllBitShuffle now passes on big-endian EMU128 with the fixes in this pull request.
> Made fixes to generic_ops-inl.h BitShuffle impl on big-endian

- hwy/contrib/math/math-inl.h
Added ToNearestInt32 to ExpImpl<float> and ExpImpl<double>, which is a wrapper around NearestInt or DemoteToNearestInt.
Also updated Exp2 to use ExpImpl::ToNearestInt32 as ExpImpl::ToNearestInt32 is more efficient on most targets, including x86, NEON, and RVV.
> Made enhancements to Exp2

- hwy/ops/arm_neon-inl.h
Reimplemented I32/U32 SumOfMulQuadAccumulate on NEON_BF16 since the vdot[q]_s32 and vdot[q]_u32 intrinsics are guaranteed to be available on the NEON_BF16 target, which requires support for the AArch64 DotProd extension.
> Added platform-specific I32/U32 SumOfMulQuadAccumulate on NEON_BF16

- hwy/ops/rvv-inl.h
This pull request optimizes the `Eq128` and `Ne128` operators with a similar approach as #2079, where the mask values are treated as partial vectors to avoid the huge overhead introduced by the operations on the large vector group coming from `VecFromMask` when LMUL is large.
> Improve the Eq128 and Ne128 performance for RVV

- hwy/ops/generic_ops-inl.h
> Revert to previous logic for GatherIndexN

- .gitignore
- MODULE.bazel
Add an alias for googletest in the MODULE.bazel.
Also, added Bazel dirs into .gitignore.
> Make tests run with Bazel8

- hwy/ops/arm_sve-inl.h
Extends the existing SatWidenMulPairwiseAccumulate operation to have a native implementation for SVE 2.
Passes the existing tests in mul_pairwise_test.cc
> Add SVE2 implementation of SatWidenMulPairwiseAccumulate

- hwy/ops/x86_128-inl.h
- hwy/ops/x86_avx3-inl.h
Updated AVX3 implementation of CompressBlendedStore to fix test failures in TestCompress on AVX3_ZEN4/AVX3_SPR with Clang.
> Fixes to CompressBlendedStore on AVX3_ZEN4/AVX3_SPR with Clang

- hwy/contrib/thread_pool/thread_pool.h
Workaround for template deduction compiler error in `WorkerAdapter::operator()(const Spin&, const Wait&)` or `WorkerAdapter::operator()(const Spin&, const Barrier&)` with MSVC 2019.
`this->CallImpl` is used in the updated implementation of `WorkerAdapter::operator()` in this pull request to avoid unwanted ADL (argument-dependent lookup) in `WorkerAdapter::operator()` and to ensure that `WorkerAdapter::CallImpl` is selected.
`WorkerAdapter::operator()` is also declared with `hwy::EnableIf` in the return type instead of a template parameter to work around template deduction compiler errors with MSVC 2019. Note that the return type of `WorkerAdapter::operator()` is still `void` with the changes in this pull request as `hwy::EnableIf<Cond>` is a typedef for `void` if `Cond` is true.
The …
> Workaround for WorkerAdapter compiler error with MSVC 2019

- hwy/base.h
Made fixes to implementation of ConvertScalarTo to work around GCC 13 or later compiler warning that can occur on x86 with the `-mavx512f` compiler option.
> Made fixes to ConvertScalarTo to work around GCC compiler warning
